#@ load("@ytt:data", "data")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gemfire
  namespace: gemfire-install
spec:
  serviceAccountName: kapp-sa
  fetch:
  - imgpkgBundle:
      image:  #@ data.values.repo.url + ":" + data.values.version
      secretRef:
        name: repo-secret
    path: gemfire/
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - gemfire/operator.yaml
      - gemfire/certificates.yaml
      - gemfire/functions.lib.yml
      inline:
        paths:
          values-update.yaml: |
            #@data/values
            ---
            namespace: gemfire-install
            name: gemfire-operator
            certManagerNamespace: ""
            cpu: ""
            memory: ""
            imagePullSecretName: "repo-secret"
            tlsSecretName: ""
            registry:
              server: ""
              username: ""
              password: ""
  deploy:
    - kapp: {}
