#@data/values-schema
---
certmanager:
  enabled: true
  package_repo:
    install: false
    repo: projects.registry.vmware.com/tkg/packages/standard/repo
    version: v2024.8.21
  package:
    install: true

#@schema/desc "Rabbitmq starter"
rabbitmq:
  #@schema/desc "package installation"
  package:
    #@schema/desc "install via carvel"
    install: true
    #@schema/desc "install repo"
    repo:
      url: rabbitmq-kubernetes.packages.broadcom.com/tanzu-rabbitmq-package-repo
      user: ""
      password: ""
    #@schema/desc "install version"
    version: 4.1.0
    #@schema/desc "operator version"
    operator_version: 4.1.0

#@schema/desc "Postgres starter"
postgres:
  #@schema/desc "package installation"
  package:
    #@schema/desc "install via carvel"
    install: true
    #@schema/desc "install repo"
    repo:
      url: tanzu-sql-postgres.packages.broadcom.com/tds-packages
      user: ""
      password: ""
    #@schema/desc "install version"
    version: v4.1.0

#@schema/desc "Gemfire starter"
gemfire:
  #@schema/desc "package installation"
  package:
    #@schema/desc "install via carvel"
    install: true
    #@schema/desc "install repo"
    repo:
      url: registry.packages.broadcom.com/tanzu-gemfire-for-kubernetes/gemfire-for-kubernetes-carvel-bundle
      user: ""
      password: ""
    #@schema/desc "install repo password"
    repo_password: ""
    #@schema/desc "install version"
    version: 2.5.0



