apiVersion: v1
kind: Secret
metadata:
  name: desired-namespaces-overlay
  namespace: tap-install
stringData:
  desired-namespace-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"metadata":{"name":"desired-namespaces"}, "kind": "ConfigMap"})
    ---
    metadata:
      annotations:
        #@overlay/match missing_ok=True
        kapp.k14s.io/exists: ""
