apiVersion: v1
kind: ConfigMap
metadata:
  name: desired-namespaces
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    namespace-provisioner.apps.tanzu.vmware.com/no-overwrite: "" #! Do not reconcile
    kapp.k14s.io/change-group: namespace-provisioner.apps.tanzu.vmware.com/delete-after-app
data:
  namespaces.yaml: |
    #@data/values
    ---
    namespaces: aaa
