#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")

#@ def dev_namespaces():
namespaces: #@ data.values.dev_namespaces
#@ end

#@overlay/match by=overlay.subset({"metadata": {"name": "desired-namespaces"}})
---
data:
  #@overlay/replace via=lambda a,_: a.replace("namespaces:", yaml.encode(dev_namespaces()))
  namespaces.yaml:
