#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: core-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: core-xsrfKey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: database-password
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harborAdminPassword
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: jobservice-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: registry-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: secretKey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 16
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: harbor-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: core-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: core-secret
    - name: core-xsrfKey
      ref:
        apiVersion: v1
        kind: Secret
        name: core-xsrfKey
    - name: database-password
      ref:
        apiVersion: v1
        kind: Secret
        name: database-password
    - name: harborAdminPassword
      ref:
        apiVersion: v1
        kind: Secret
        name: harborAdminPassword
    - name: jobservice-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: jobservice-secret
    - name: registry-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: registry-secret
    - name: secretKey
      ref:
        apiVersion: v1
        kind: Secret
        name: secretKey
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        core:
          secret: #@ base64.decode("$(.core-secret.data.pass)")
          xsrfKey: #@ base64.decode("$(.core-xsrfKey.data.pass)")
        database:
          password: #@ base64.decode("$(.database-password.data.pass)")
        harborAdminPassword: #@ base64.decode("$(.harborAdminPassword.data.pass)")
        jobservice:
          secret: #@ base64.decode("$(.jobservice-secret.data.pass)")
        registry:
          secret: #@ base64.decode("$(.registry-secret.data.pass)")
        secretKey: #@ base64.decode("$(.secretKey.data.pass)")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"