#@data/values-schema
---
namespace: rabbitmq-install

repo:
  url: rabbitmq-kubernetes.packages.broadcom.com/tanzu-rabbitmq-package-repo
  user: ""
  password: ""

version: 4.3.2
operator_version: 4.3.2


