#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: #@ data.values.namespace
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ "{}-kapp-role-binding".format(data.values.namespace)
  namespace: #@ data.values.namespace
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: harbor
  namespace: #@ data.values.namespace
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: harbor-values
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: harbor-values-generated-secrets
spec:
  serviceAccountName: kapp-sa
  packageRef:
    refName: harbor.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
