#@ load("@ytt:data", "data")

#@ eks_role  = "arn:aws:iam::" + data.values.aws_services.account_id + ":role/tap-aws-services"

#@ def aws_services_values():
role_arn: #@ eks_role

postgresql:
  enabled: true
  region: #@ data.values.aws_services.region
  provider_config_ref:
    name: aws-provider
  infrastructure:
    subnet_group:
      name: tap-aws-services
    security_groups:
      - id:  #@ data.values.aws_services.rds.security_group
  instance_configuration:
    instance_class: db.t4g.micro
    engine_version: "15.5"
    skip_final_snapshot: true
    publicly_accessible: false
    maintenance_window: Mon:00:00-Mon:03:00
#@ end