#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:overlay", "overlay")

#@ def dev_namespaces():
namespaces: #@ data.values.dev_namespaces
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name":"desired-namespaces"}, "kind": "ConfigMap"})
---
data:
  #@overlay/replace via=lambda a,_: a.replace("namespaces: aaa", yaml.encode(dev_namespaces()))
  namespaces.yaml: |
