apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: scdf.tanzu.japan.com.1.6.6
spec:
  refName: scdf.tanzu.japan.com
  version: 1.6.6
  valuesSchema:
    openAPIv3:
      title: scdf.tanzu-jp values schema
      properties:
        namespace:
          type: string
          default: default
        postgres:
          type: object
          additionalProperties: false
          properties:
            count:
              type: integer
              default: 1
            storage_class:
              type: string
              default: default
            instance_version:
              type: string
              default: postgres-17
        rabbitmq:
          type: object
          additionalProperties: false
          properties:
            count:
              type: integer
              default: 1
        repo:
          type: object
          additionalProperties: false
          properties:
            url:
              type: string
              default: registry.packages.broadcom.com
            user:
              type: string
              default: ""
            password:
              type: string
              default: ""
        version:
          type: string
          default: 1.6.6
        task_runner_version:
          type: string
          default: 2.11.8
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/scdf.tanzu.japan.com/1.6.6
      template:
        - ytt:
            valuesFrom:
              - downwardAPI:
                  items:
                    - name: namespace
                      fieldPath: metadata.namespace
      deploy:
      - kapp: {}
