#@data/values-schema
---
namespace: default


standard:
  package_repo:
    install: true
    repo: projects.packages.broadcom.com/tkg/packages/standard/repo
    version: v2025.6.18

cert-manager:
  install: true
  ref_suffix: tanzu.vmware.com
  #@schema/type any=True
  package: {}

contour:
  install: true
  ref_suffix: tanzu.vmware.com
  #@schema/type any=True
  package:
    envoy:
      service:
        type: LoadBalancer

harbor:
  install: true
  ref_suffix: tanzu.vmware.com
  secrets_template: true
  #@schema/type any=True
  package:
    hostname: harbor.example.com
    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: tkg-ds
          size: 200Gi
        jobservice:
          jobLog:
            storageClass: tkg-ds
            size: 1Gi
        database:
          storageClass: tkg-ds
          size: 1Gi
        redis:
          storageClass: tkg-ds
          size: 1Gi
        trivy:
          storageClass: tkg-ds
          size: 5Gi

rabbitmq:
  install: true
  ref_suffix: tanzu.japan.com
  #@schema/type any=True
  package:
    repo:
      url: rabbitmq-kubernetes.packages.broadcom.com/tanzu-rabbitmq-package-repo
      user: ""
      password: ""
    version: 4.1.0
    operator_version: 4.1.0

postgres:
  install: true
  ref_suffix: tanzu.japan.com
  #@schema/type any=True
  package:
    repo:
      url: tanzu-sql-postgres.packages.broadcom.com/vmware-sql-postgres-operator
      user: ""
      password: ""
    version: v4.1.0

gemfire:
  install: true
  ref_suffix: tanzu.japan.com
  #@schema/type any=True
  package:
    repo:
      url: registry.packages.broadcom.com/tanzu-gemfire-for-kubernetes/gemfire-for-kubernetes-carvel-bundle
      user: ""
      password: ""
    version: 2.5.0
    gmc:
      install: true
      repo:
        url: registry.packages.broadcom.com/gemfire-management-console/gemfire-management-console
      version: 1.3.0

gpss:
  install: true
  ref_suffix: tanzu.japan.com
  #@schema/type any=True
  package:
    repo:
      url: helm-gpss-operator
      user: ""
      password: ""
    version: 1.0.0
    controller:
      repo:
        url: controller
      version: 1.0.0

etcd:
  install: true
  ref_suffix: tanzu.japan.com
  #@schema/type any=True
  package:
    namespace: gpss-etcd
