#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: scdf-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: rmq
      ref:
        apiVersion: v1
        kind: Secret
        name: rmq-1-default-user
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        scdf:
          binder:
            rabbit:
              host: #@ base64.decode("$(.rmq.data.host)")
              username: #@ base64.decode("$(.rmq.data.username)")
              password: #@ base64.decode("$(.rmq.data.password)")
---
apiVersion: v1
kind: Secret
metadata:
  name: scdf-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"