apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: gpss.tanzu.japan.com
spec:
  displayName: "Tanzu GPSS for k8s"
  shortDescription: "Tanzu GPSS for k8s"
  supportDescription: "https://carvel.dev/"
  providerName: "Broadcom"
  maintainers:
  - name: "Machi Hoshino"
