#@ load("@ytt:data", "data")

#@ if data.values.cert_injection_webhook.enabled:
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: #@ data.values.namespace
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ "{}-kapp-role-binding".format(data.values.namespace)
  namespace: #@ data.values.namespace
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-injection-webhook
  namespace: #@ data.values.namespace
spec:
  serviceAccountName: kapp-sa
  fetch:
  - imgpkgBundle:
      image:  #@ data.values.cert_injection_webhook.repo + ":" + data.values.cert_injection_webhook.version
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - config/
      inline:
        paths:
          values.yaml: |
            #@data/values
            ---
            labels:
              - "app.kubernetes.io/cluster"
        pathsFrom:
          - secretRef:
              name: cert-injection-webhook-values-secrets
  deploy:
    - kapp: {}
#@ end