#@ load("@ytt:data", "data")

#@ if data.values.cert_injection_webhook.enabled:
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: cert-injection-webhook-values-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
    kapp.k14s.io/change-rule: "upsert after upserting certificate"
spec:
  inputResources:
    - name: gpss-server-tls
      ref:
        apiVersion: v1
        kind: Secret
        name: gpss-server-tls
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        
        #@ cert = ""
        #@ cert += base64.decode("$(.gpss-server-tls.data.ca\.crt)") + "\n"
        #@ cert += base64.decode("$(.gpss-server-tls.data.tls\.crt)") + "\n"
        #@ cert += base64.decode("$(.gpss-server-tls.data.tls\.key)") + "\n"
        ---
        ca_cert_data: #@ cert
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-injection-webhook-values-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"
#@ end
