#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgres-pass
  namespace: tmc-local
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: minio-pass
  namespace: tmc-local
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)