#@data/values-schema
---
namespace: tdf-install

ingress:
  enabled: true
  domain: dataflow.example.com

repo:
  url: tanzu-dataflow.packages.broadcom.com/dataflow
  user: ""
  password: ""
version: 2.1.3