#@data/values-schema
---
namespace: gemfire-install

repo:
  url: registry.packages.broadcom.com/tanzu-gemfire-for-kubernetes/gemfire-for-kubernetes-carvel-bundle
  user: ""
  password: ""
repo_password: ""
version: 2.5.0

gmc:
  install: true
  ingress:
    enabled: false
    domain: example.com
  repo:
    url: registry.packages.broadcom.com/gemfire-management-console/gemfire-management-console
  version: 1.3.0
