#@data/values-schema
---
certmanager:
  enabled: true
  package_repo:
    install: false
    repo: projects.registry.vmware.com/tkg/packages/standard/repo
    version: v2024.8.21
  package:
    install: true

openldap:
  enabled: true
  ssl: false
  rootdn: dc=tanzu,dc=net
  adminpassword: adminpassword
  ldif: |
    dn: dc=tanzu,dc=net
    dc: tanzu
    objectClass: dcObject
    objectClass: organization
    o: Tanzu, Inc
    
    dn: ou=core,dc=tanzu,dc=net
    objectClass: organizationalUnit
    ou: core
    
    dn: cn=tpviewer,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpviewer
    sn: TP Viewer
    uid: tpviewer
    mail: tpviewer@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmin,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpadmin
    sn: TP Admin
    uid: tpadmin
    mail: tpadmin@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmins,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpadmins
    description: Tanzu Platform Admins
    member: cn=tpadmin,ou=core,dc=tanzu,dc=net
    
    dn: cn=tpviewers,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpviewers
    description: Tanzu Platform Viewer
    member: cn=tpviewer,ou=core,dc=tanzu,dc=net
tp:
  flavor: full
  profile: evaluation
  version: '10.0.0-oct-2024-rc.533-vc0bb325'
  storage_class: tkg-ds
  keep_pvc: false
  ingress:
    host: tp.example.com
    self_signed_cert: true
    certificate: ""
    privateKey: ""
  salt_disabled: true
  vcf_disabled: true
  imageRegistry:
    server: harbor.example.com
    username: admin
    password: ""
    repo: tpk8s/10.0.0
  organization:
    name: default
  namespace: tanzusm
  ldap_enabled: true
  oauthProviders: [{}]
