#@data/values-schema
---
certmanager:
  enabled: true
  package_repo:
    install: false
    repo: projects.registry.vmware.com/tkg/packages/standard/repo
    version: v2024.8.21
  package:
    install: true

openldap:
  enabled: true
  image: index.docker.io/bitnami/openldap@sha256:8e3f28db7a8c05d7db99ec688b8ca1044f0deaf8f98ea5b1f71c42276e3c1583
  ssl: false
  rootdn: dc=tanzu,dc=net
  adminpassword: adminpassword
  ldif: |
    dn: dc=tanzu,dc=net
    dc: tanzu
    objectClass: dcObject
    objectClass: organization
    o: Tanzu, Inc
    
    dn: ou=core,dc=tanzu,dc=net
    objectClass: organizationalUnit
    ou: core
    
    dn: cn=tpviewer,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpviewer
    sn: TP Viewer
    uid: tpviewer
    mail: tpviewer@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmin,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpadmin
    sn: TP Admin
    uid: tpadmin
    mail: tpadmin@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmins,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpadmins
    description: Tanzu Platform Admins
    member: cn=tpadmin,ou=core,dc=tanzu,dc=net
    
    dn: cn=tpviewers,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpviewers
    description: Tanzu Platform Viewer
    member: cn=tpviewer,ou=core,dc=tanzu,dc=net
tp:
  flavor: full
  profile: evaluation
  version: '10.0.0-oct-2024-rc.533-vc0bb325'
  storage_class: tkg-ds
  hack:
    add_limit_to_clickhouse: false
    change_pvc_orphan_delete_strategy: true
    reduce_kafka_replica: true
    reduce_redis_replica: true
    make_tmc_xsmall: true
    salt_disabled: true
    vcf_disabled: true
    fix_promtheus_too_small: true
  ldap_enabled: true
  rsa_builder:
    openssl_image: index.docker.io/alpine/openssl@sha256:7f9e867564f38e409098eb6438e982bcc26b805942ce6524ad770534c0afdafb
    kubectl_image: index.docker.io/bitnami/kubectl@sha256:671516f53dd61f1e7d1dc178ba30d47faecc6caaa1e8c2a0f53d3d939f11c077
  ingress:
    host: tp.example.com
    self_signed_cert: true
    certificate: ""
    privateKey: ""
  imageRegistry:
    server: harbor.example.com
    username: admin
    password: ""
    repo: tpk8s/10.0.0
  organization:
    name: default
  namespace: tanzusm
  oauthProviders: [{}]
