#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
#! https://github.gwd.broadcom.net/TNZ/ensemble-self-managed/blob/master/installer/pkg/install/feature_flag_step.go

#@ def feature_flags()
#! https://github.gwd.broadcom.net/TNZ/ensemble-self-managed/blob/723bc39ddc099a65a4aaa04ad3c478f3b9ca8506/installer/pkg/install/resources/feature-flags/feature-flags.lib.yml
featureFlags:
  global:
    - name: ENABLE_TAS_HUB_COLLECTORS
      value: true
    - name: ENABLE_HUB_LCM_ORCHESTRATOR
      value: true
    - name: TELEMETRY_PUBLISHING_FLAG
      value: true
    - name: ENABLE_AZURE_ELEVATED_ACCESS_UI
      value: true
    - name: SUBSCRIPTION_MANAGER_ARIA_SERVICES_ONBOARDING
      value: true
    - name: LCM_VRA_AAP_ACTIVATION
      value: true
    - name: ENABLE_SUPPRESSIONS_UI
      value: true
    - name: feature-limited-accounts
      value: true
    - name: ENABLE_MIGRATION_WAVE_UI
      value: true
    - name: feature-limited-aria-accounts
      value: true
    - name: ENDPOINT_MGMT_CLOUDACCOUNT_PROXY_MGMT
      value: true
    - name: ENABLE_VMW_CLOUD_VISIBILITY
      value: true
    - name: ENABLE_FINDINGS_SOURCES_UI
      value: true
    - name: eds_print_es_delete_relationships_of_del_ent
      value: true
    - name: ENABLE_SM_NOTIFICATION_TARGETS
      value: false
    - name: FREEMIUM_IS_FREE
      value: false
    - name: ENABLE_VCF_COLLECTORS_UI
      value: true
    - name: NOTIFICATIONS_TARGET_TYPE_EMAIL
      value: true
    - name: ENABLE_GOVERNANCE_FINDINGS_UI
      value: true
    - name: ENABLE_LIVE_AGENT
      value: true
    - name: ENABLE_INSIGHTS
      value: true
    - name: tier-freemium
      value: true
    - name: ENABLE_GOVERNANCE_RECOMMENDATION_COST_ADVISOR_FINDINGS_UI
      value: true
    - name: ENABLE_CUSTOM_POLICY_EXPLORE_UI
      value: true
    - name: CREDENTIAL_CSP_PROJECT_VALIDATIONS_ENABLED
      value: true
    - name: FEATURE_AZURE_BULK_ONBOARDING_IN_HUB
      value: true
    - name: ENABLE_RULES_UI
      value: true
    - name: ENABLE_VROPS_COLLECTION
      value: true
    - name: MIGRATION_SERVICE
      value: true
    - name: ENABLE_MIGRATION_CENTER
      value: true
    - name: ENABLE_GCP_UI
      value: true
    - name: ENABLE_NOTIFICATION_TARGETS_UI
      value: true
    - name: ENABLE_DRIFT_ENHANCED_DIFF_UI
      value: true
    - name: ENABLE_MULTI_REGION_MAS
      value: true
    - name: ENABLE_MULTI_REGION
      value: true
    - name: MIGRATION_SERVICE_INVENTORY
      value: true
    - name: GUARDRAILS_API
      value: true
    - name: GUARDRAILS_UI
      value: true
    - name: NOTIFICATIONS_TARGET_TYPE_SLACK
      value: true
    - name: FEATURE_CSP_PROJECTS_MANAGEMENT_IN_HUB
      value: true
    - name: ENABLE_NOTIFICATION_RULES_UI
      value: true
    - name: ENABLE_AWS_ELEVATED_ACCESS_UI
      value: true
    - name: FEATURE_AWS_BULK_ONBOARDING_IN_HUB
      value: true
    - name: MIGRATION_SERVICE_VMC
      value: true
    - name: ENABLE_GOVERNANCE
      value: true
    - name: ENABLE_PROXY_MGMT
      value: true
    - name: MIGRATION_SERVICE_DB
      value: true
    - name: FEATURE_AZURE_BULK_ONBOARDING_WITH_ELEVATED_ACCESS
      value: true
    - name: ENABLE_DASHBOARD_API
      value: true
    - name: ENABLE_ASSESSMENT_CENTER_UI
      value: true
    - name: ENABLE_HUB_QUERY_UI
      value: true
    - name: ENABLE_ONLY_ELASTICSEARCH_QUERIES_API
      value: true
    - name: ENABLE_IA_NAV_UI
      value: true
    - name: ENABLE_NEW_EXPLORE_VIEW_UI
      value: true
    - name: ENABLE_APP_MANAGERS_UI
      value: true
    - name: ENABLE_NAVBAR_RESTRUCTURE_UI
      value: true
    - name: ENABLE_ACCESS_CONTROL_UI
      value: false
    - name: ENABLE_K8S_OPERATIONS_NAV_ITEM
      value: true
    - name: ENABLE_SPRING_DATA_INGESTION_PUBLIC_CLOUD_VM_API
      value: false
    - name: ENABLE_SPRING_DATA_INGESTION_API
      value: true
    - name: ENABLE_TAS_SERVICE_FOUNDATION_VIEW
      value: true
    - name: ENABLE_SPRING_POLICIES_UI
      value: true
    - name: ENABLE_GIT_REPOSITORY_UI
      value: true
    - name: ENABLE_ENDPOINT_REPO_VIEW_UI
      value: true
    - name: ENABLE_POLICY_ENGINE
      value: true
    - name: ENABLE_POLICY_PROVIDERS_DEFAULT_SPRING_POLICIES_API
      value: true
    - name: ENABLE_K8S_POLICIES_UI
      value: true
    - name: ENABLE_MANAGEMENT_ENDPOINT_CREDENTIAL_SCOPES
      value: true
    - name: ENABLE_SALTSTACK_HOME_WIDGET_UI
      value: false
    - name: ENABLE_SALTSTACK_STANDALONE_UI
      value: false
    - name: ENABLE_APP_DASHBOARD_LIB_VIEW_UI
      value: true
    - name: ENABLE_OBS_CONTEXTUAL_LOGS_UI
      value: true
    - name: ENABLE_OBSERVABILITY_OVERLAY_FEATURE
      value: true
    - name: ENABLE_OBSERVABILITY_ALERTS
      value: true
    - name: ENABLE_K8S_LCM_LTKGS_UI
      value: true
    - name: ENABLE_PLATFORM_RBAC_API
      value: true
    - name: ENABLE_BUSINESS_APPLICATION_CURATION
      value: true
    - name: ENABLE_APP_CURATION
      value: true
    - name: ENABLE_MULTISPACE_BA_TOPO_UI
      value: true
    - name: ENABLE_SALTSTACK_ADMIN_UI
      value: true
    - name: NOTIFICATIONS_TARGET_TYPE_WEBHOOK
      value: true
    - name: ENABLE_SOFTWARE_CATALOG_UI
      value: true
    - name: ENABLE_ARIA_CATALOGS
      value: true
    - name: ENABLE_SPACE_TOPOLOGY_API
      value: true
    - name: ENSEMBLE_DOCUMENT_SERVICE
      value: true
    - name: ENABLE_OBS_LOG_PATTERNS_UI
      value: true
    - name: ENABLE_OBSERVABILITY_METRIC_OVERLAY_FEATURE
      value: true
    - name: ENABLE_OBSERVABILITY_ALERT_RUNBOOK_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_LOGS
      value: true
    - name: ENABLE_CONTAINER_APPS_RESTART_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_RUNNING_REPLICAS_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_ENV_VARS_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_RESOURCES_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_DELETE_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_SCALE_UI
      value: true
    - name: ENABLE_SERVICE_INSTANCE_DETAILS_UI
      value: true
    - name: ENABLE_SPACE_SERVICE_HTTP_DETAILS_UI
      value: true
    - name: ENABLE_SERVICE_INSTANCES_UI
      value: true
    - name: ENABLE_APP_OBSERVABILITY_POD_LOGS
      value: true
    - name: ENABLE_SPACE_SERVICE_DETAILS_UI
      value: true
    - name: ENABLE_CONTAINER_APPS_START_STOP_UI
      value: true
    - name: ENABLE_APP_BA_REFRESH_VIEW_UI
      value: true
    - name: ENABLE_DASHBOARD_OVERVIEW_TAB_UI
      value: true
    - name: ENABLE_SPACES_UI
      value: true
    - name: ENABLE_SPACE_POLICIES_UI
      value: true
    - name: ENABLE_NETWORKING_UI
      value: true
    - name: ENABLE_INCREMENTAL_APP_DISCOVERY
      value: true
    - name: ENABLE_APPLICATION_ENGINE
      value: true
    - name: ENABLE_SPACES_GA_UI
      value: true
    - name: ENABLE_MANAGEMENT_ENDPOINT_ONBOARDING_INFO
      value: true
    - name: ENABLE_OBSERVABILITY_RELATED_ALERTS_WIDGET_UI
      value: true
    - name: ENABLE_OBSERVABILITY_WEBHOOK_TEMPLATES_UI
      value: true
    - name: ENABLE_CORRELATION_IN_RULE_SVC
      value: true
    - name: ENABLE_OBSERVABILITY_NOTIFICATION_TARGETS_UI
      value: true
    - name: ENABLE_PLATFORM_TAB_UI
      value: true
    - name: ENABLE_UCP_UI
      value: true
    - name: ENABLE_VCENTER_COLLECTORS_UI
      value: true
    - name: ENABLE_ONBOARDING_EXPERIENCE_UI
      value: true
    - name: ENABLE_CF_GCP_COLLECTOR_VIEW
      value: true
    - name: DE_DUP_DELTA_EVENTS
      value: true
    - name: ENABLE_APPLICATIONS_BACKING_SERVICES_UI
      value: true
    - name: ENABLE_PLATFORM_HEALTH_OBSERVABILITY
      value: true
  flavor_full:
    - name: ENABLE_TAP_KUBERNETES_MANAGEMENT
      value: true
    - name: ENABLE_CAPABILITIES_CATALOG_UI
      value: true
    - name: ENABLE_K8S_LCM_UI
      value: true
    - name: ENABLE_CREDENTIAL_MANAGEMENT_TAP_GSLB_UI
      value: true
    - name: ENABLE_OBS_K8S_UI
      value: true
    - name: ENABLE_DEVELOPER_SERVICE_WORKFLOWS_GA_UI
      value: true
    - name: ENABLE_UCO_UI
      value: true
    - name: ENABLE_CORDON_UNCORDON_DRAIN_ACTIONS_UI
      value: true
    - name: APP_ENGINE_APPLICATION_DISCOVERY
      value: true
    - name: ENABLE_SPRING_DATA_INGESTION_APP_ENGINE_API
      value: true
    - name: ENABLE_CONTAINER_APPS_UI
      value: true
    - name: ENABLE_APPLICATION_PERFORMANCE_OBS_UI
      value: true
    - name: ENABLE_APPLICATION_PERFORMANCE_OBS_SPRING_UI
      value: true
    - name: ENABLE_OBSERVABILITY_NOTIFICATION_TARGETS_EMAIL_UI
      value: true
    - name: ENABLE_OBSERVABILITY_ALERT_TRIGGERED_OVERLAY_UI
      value: true
    - name: ENABLE_OBSERVABILITY_METRIC_CHART_OPTIONS
      value: true
    - name: ENABLE_OBS_UI_WIDGET_ACTIONS
      value: true
    - name: ENABLE_OBSERVABILITY_KUBERNETES_ALERTS_UI
      value: true
    - name: ENABLE_OBSERVABILITY_KUBERNETES_WIDGETS
      value: true
    - name: ENABLE_OBSERVABILITY_ALERT_RBAC_UI
      value: true
#@ end


#@ ff = []
#@ enable_tia = data.values.tp.TanzuIntelligentAssist.enable != "False"
#@ full_mode = data.values.tp.flavor == "full"

#@ ff_global = feature_flags()["featureFlags"]["global"]
#@ ff_flavor_full = feature_flags()["featureFlags"]["flavor_full"]

#@ for f in ff_global:
#@   ff.append(f)
#@ end

#@ if full_mode:
#@   for f in ff_flavor_full:
#@     ff.append(f)
#@   end
#@ end
#@ ff.append({"name": "ENABLE_FULL_MODE", "value": full_mode})


#@ ff.append({"name": "ENABLE_INTELLIGENT_ASSIST", "value": enable_tia})
#@ ff.append({"name": "ENABLE_TIA_IN_HEADER", "value": enable_tia})
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: #@ data.values.tp.namespace
  name: ff-config
data:
  ff-config.json: #@ json.encode({"FeatureFlags": ff})
    
