apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tpk8s-toolkit-capabilities.tanzu.japan.com
spec:
  displayName: "TP Toolkit Capabilites (Unofficial)"
  shortDescription: "TP Toolkit Capabilites (Unofficial)"
  supportDescription: "https://carvel.dev/"
  providerName: "Broadcom"
  maintainers:
  - name: "Machi Hoshino"
