#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")


#@ def gpss_config():
ListenAddress:
  Host: ""
  Port: 5000
Gpfdist:
  Host: ""
  Port: 8090
Cluster:
  Id: #@ data.values.name
  Port: 5001
  etcd:
    Endpoints:
     - etcd.gpss-etcd:2379
#@ end

---
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: #@ data.values.namespace
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: gpss.gpdb.io/v1
kind: GpssCluster
metadata:
  annotations: {}
  name: #@ data.values.name
  namespace: #@ data.values.namespace
spec:
  service:
    gpfdist: LoadBalancer
    gpss: LoadBalancer
  size: #@ data.values.replicas
  image: #@ data.values.image
  resources: #@ data.values.resource
  pull_secret: regsecret
  gpss_config: #@ json.encode(gpss_config())
