apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-statefulset.tanzu.japan.com.1.8.0
spec:
  refName: tap-statefulset.tanzu.japan.com
  version: 1.8.0
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tap-statefulset.tanzu.japan.com/1.8.0
      template:
      - ytt: {}
      deploy:
      - kapp: {}