apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-setup.tanzu.japan.com.1.9.0
spec:
  refName: tap-setup.tanzu.japan.com
  version: 1.9.0
  valuesSchema:
    openAPIv3:
      title: tap-setup.tanzu-jp values schema
      properties:
        dev_namespaces:
          type: object
          description: Developer namespaces
          default:
          - name: dev-ns1
            gitops: true
            bucketrepo: true
            blank_pipeline_and_scan: true
        tls:
          type: object
          additionalProperties: false
          description: TLS config
          properties:
            enabled:
              type: boolean
              default: false
            crt:
              type: string
              default: dummy
            key:
              type: string
              default: dummy
        gitops:
          type: object
          additionalProperties: false
          description: gitops credentials
          properties:
            enabled:
              type: boolean
              default: true
            url:
              type: string
              default: dummy
            username:
              type: string
              default: dummy
            password:
              type: string
              default: dummy
        bucketrepo:
          type: object
          additionalProperties: false
          description: bucketrepo for faster download
          properties:
            enabled:
              type: boolean
              default: true
            image:
              type: string
              default: jenkinsxio/bucketrepo
        tap_gui_viewer:
          type: object
          additionalProperties: false
          description: Enable TAP GUI viewer
          properties:
            enabled:
              type: boolean
              default: true
            is_view_cluster:
              type: boolean
              default: false
        blank_pipeline_and_scan:
          type: object
          additionalProperties: false
          description: Place blank pipeline and scan template
          properties:
            enabled:
              type: boolean
              default: true
            test_image:
              type: string
              default: alpine
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tap-setup.tanzu.japan.com/1.9.0/common
      template:
      - ytt: {}
      deploy:
      - kapp: {}
