apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tap-setup.tanzu.japan.com
spec:
  displayName: "Setup TAP"
  shortDescription: "Setup TAP"
  supportDescription: "https://carvel.dev/"
  providerName: "VMware"
  maintainers:
  - name: "Machi Hoshino"
