#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: tp-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: redis-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: clickhouse-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgres-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-access-key
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-readonly-access-key
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-secret-key
  namespace: #@ data.values.tp.namespace
spec:
  length: 40
  digits: 10
  uppercaseLetters: 10
  lowercaseLetters: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-readonly-secret-key
  namespace: #@ data.values.tp.namespace
spec:
  length: 40
  digits: 10
  uppercaseLetters: 10
  lowercaseLetters: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id
  namespace: #@ data.values.tp.namespace
spec:
  length: 36
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: encryption-key
  namespace: #@ data.values.tp.namespace
spec:
  length: 44
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: tp-app-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: ensemble-user-service-pass
  namespace: #@ data.values.tp.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)