#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: rsa-key
  namespace: #@ data.values.tp.namespace
---
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: jwt-key
  namespace: #@ data.values.tp.namespace