#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: RSAKey
metadata:
  name: jwt-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rsa-role
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
rules:
  - apiGroups: ['']
    resources: ['secret']
    verbs: ['create', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rsa-role-bindings
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rsa-role
subjects:
  - kind: ServiceAccount
    name: rsa-sa
    namespace: #@ data.values.tp.namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsa-sa
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: rsa-create
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  template:
    spec:
      serviceAccountName: rsa-sa
      restartPolicy: Never
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: openssl
          image: #@ data.values.tp.rsa_builder.openssl_image
          command:
            - /bin/sh
            - -c
          args:
            - |
              openssl genrsa -out /data/key.pem 2048 ; 
              openssl rsa -in /data/key.pem -pubout -out /data/pub.pem ;
              chmod 777 /data/*
          volumeMounts:
            - mountPath: /data
              name: data
        - name: kubectl
          image: #@ data.values.tp.rsa_builder.kubectl_image
          command:
            - kubectl
          args:
            - create
            - secret
            - generic
            - rsa-key
            - --from-file=key.pem=/data/key.pem
            - --from-file=pub.pem=/data/pub.pem
          volumeMounts:
            - mountPath: /data
              name: data
---
apiVersion: v1
kind: Secret
metadata:
  name: rsa-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp,k14s.io/owned-for-deletion: ""
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"