apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: codegen-workload-1
spec:
  ytt: |
    #@ load("@ytt:data", "data")    
    apiVersion: carto.run/v1alpha1
    kind: Workload
    metadata:
      name: #@ "{}-tanzu-java-web-app".format(data.values.workload.metadata.name)
      labels:
        apps.tanzu.vmware.com/workload-type: web
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        app.kubernetes.io/part-of: #@ "{}-tanzu-java-web-app".format(data.values.workload.metadata.name)
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName
      params:
      - name: annotations
        value:
          autoscaling.knative.dev/minScale: "1"
      source:
        git:
          url: #@ data.values.source.url
          ref:
            branch: #@ data.values.source.revision
        subPath: tanzu-java-web-app
---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: codegen-workload-2
spec:
  ytt: |
    #@ load("@ytt:data", "data") 
    apiVersion: carto.run/v1alpha1
    kind: Workload
    metadata:
      name: #@ "{}-java-server-side-ui".format(data.values.workload.metadata.name)
      labels:
        apps.tanzu.vmware.com/workload-type: web
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/auto-configure-actuators: "true"
        app.kubernetes.io/part-of: #@ "{}-java-server-side-ui".format(data.values.workload.metadata.name)
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName
      params:
      - name: annotations
        value:
          autoscaling.knative.dev/minScale: "1"
      build:
        env:
        - name: BP_MAVEN_POM_FILE
          value: dummy
      source:
        git:
          url: #@ data.values.source.url
          ref:
            branch: #@ data.values.source.revision
        subPath: java-server-side-ui
