apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: codegen-run
spec:
  outputs:
    url: metadata.annotations.generated-git-url
    branch: metadata.annotations.generated-git-branch
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: $(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
      annotations: $(runnable.metadata.annotations)$
    spec:
      taskRef:
        kind: ClusterTask
        name: jenkins-task
      params: $(runnable.spec.inputs.tekton-params)$