#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
type: Opaque
stringData:
  url: #@ data.values.jenkins.url
  username: #@ data.values.jenkins.username 
  password: #@ data.values.jenkins.password
