apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: yaml2source
spec:
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: codegen
    templateRef:
      kind: ClusterSourceTemplate
      name: codegen-template
    sources:
    - resource: source-provider
      name: source
  - name: workload-provider-1
    templateRef:
      kind: ClusterTemplate
      name: codegen-workload-1
    sources:
    - resource: codegen
      name: source
  - name: workload-provider-2
    templateRef:
      kind: ClusterTemplate
      name: codegen-workload-2
    sources:
    - resource: codegen
      name: source
  selectorMatchExpressions:
  - key: apps.tanzu.vmware.com/workload-type
    operator: In
    values:
    - yaml2source
