apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: provider.config.aws.crossplane.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "crd"
spec:
  group: aws.crossplane.io
  versions:
    - name: v1beta1
  names:
    kind: ProviderConfig
  scope: Namespaced
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting crd"
spec:
  userServiceAccount: true
