#@ load("@ytt:data", "data")
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    kapp.k14s.io/change-group: "crd"
  name: upbound-provider-family-aws
spec:
  package: #@ data.values.crossplane.aws.repo + ":" + data.values.crossplane.aws.tag
  controllerConfigRef:
    name: upbound-provider-aws
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    kapp.k14s.io/change-group: "crd"
  name: upbound-provider-aws-ecs
spec:
  package: #@ data.values.crossplane.ecs.repo + ":" + data.values.crossplane.ecs.tag 
  controllerConfigRef:
    name: upbound-provider-aws
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    kapp.k14s.io/change-group: "crd"
  name: upbound-provider-aws-ec2
spec:
  package: #@ data.values.crossplane.ec2.repo + ":" + data.values.crossplane.ec2.tag
  controllerConfigRef:
    name: upbound-provider-aws
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    kapp.k14s.io/change-group: "crd"
  name: upbound-provider-aws-elbv2
spec:
  package: #@ data.values.crossplane.elbv2.repo + ":" + data.values.crossplane.elbv2.tag
  controllerConfigRef:
    name: upbound-provider-aws
