#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providerconfigs.aws.upbound.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "crd"
spec:
  group: aws.upbound.io
  versions:
    - name: v1beta1
  names:
    kind: ProviderConfig
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  annotations:
     kapp.k14s.io/change-rule: "upsert after upserting crd"
spec:
  credentials:
    source: IRSA
