#@ load("@ytt:data", "data")
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  annotations:
    kapp.k14s.io/change-group: "crd"
  name: provider-aws
spec:
  package: #@ data.values.crossplane.aws.repo + ":"  + data.values.crossplane.aws.tag
  controllerConfigRef:
    name: provider-aws
