---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: dev.registry.tanzu.vmware.com/build-service/bundle@sha256:c06384097223c1be975eb377bd05dcbb2adba2ad2a2019ebddcd72a23a9d7938
  image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:c06384097223c1be975eb377bd05dcbb2adba2ad2a2019ebddcd72a23a9d7938
kind: ImagesLock
