#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: core_secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: core_xsrfkey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: database_password
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor_admin_password
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: jobservice_secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: registry_secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: secretkey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 16
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: harbor-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: core_secret
      ref:
        apiVersion: v1
        kind: Secret
        name: core_secret
    - name: core_xsrfkey
      ref:
        apiVersion: v1
        kind: Secret
        name: core_xsrfkey
    - name: database_password
      ref:
        apiVersion: v1
        kind: Secret
        name: database_password
    - name: harbor_admin_password
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor_admin_password
    - name: jobservice_secret
      ref:
        apiVersion: v1
        kind: Secret
        name: jobservice_secret
    - name: registry_secret
      ref:
        apiVersion: v1
        kind: Secret
        name: registry_secret
    - name: secretkey
      ref:
        apiVersion: v1
        kind: Secret
        name: secretkey
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        core:
          secret: #@ base64.decode("$(.core_secret.data.pass)")
          xsrfKey: #@ base64.decode("$(.core_xsrfkey.data.pass)")
        database:
          password: #@ base64.decode("$(.database_password.data.pass)")
        harbor_admin_password: #@ base64.decode("$(.harbor_admin_password.data.pass)")
        jobservice:
          secret: #@ base64.decode("$(.jobservice_secret.data.pass)")
        registry:
          secret: #@ base64.decode("$(.registry_secret.data.pass)")
        secretkey: #@ base64.decode("$(.secretkey.data.pass)")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"