apiVersion: v1
kind: Namespace
metadata:
  name: scdf
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Secret
metadata:
  name: scdf-registry
  namespace: scdf
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: scdf
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update  
secrets:
  - name: scdf-registry
imagePullSecrets:
  - name: scdf-registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: scdf
secrets:
  - name: scdf-registry
imagePullSecrets:
  - name: scdf-registry
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-kapp-role-binding
  namespace: postgres-install
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: postgres-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin