#@data/values-schema
---
backstage:
  enabled: true
  workload:
    publish:
      repo: myrepo/lib
    lite: true
    hastests: true
    namespace: demo
    image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:29f978561d7d931c9a118c167eae905ce41990131013339aaff10c291ac6c42b
  plugin:
    name: "@mhoshi-vm/plugin-crossplane-aws"
    version: 0.1.2

crossplane:
  tag: v0.45.0
  repo: xpkg.upbound.io/upbound

aws:
  accountId: ""
  roleName: "tap-ecs"
  cluster: ""
  region: us-west-2
  vpcId: vpc-xxxxx
  alb:
    enabled: true
    public: false
    subnets:
    - subnet1
  ecs:
    public: false
    subnets:
    - private-subnet1
