#@data/values-schema
---
#@schema/desc "Developer namespaces"

#@schema/type any=True
dev_namespaces: 
- name: dev-ns1
  gitops: "true"
  bucketrepo: "true"
  blank_pipeline_and_scan: "true"
  labels:
    pod-security.kubernetes.io/enforce: baseline
  
#@schema/desc "TLS config"
tls:
  enabled: false
  crt: dummy
  key: dummy

#@schema/desc "gitops credentials"
gitops:
  enabled: true
  url: dummy
  username: dummy
  password: dummy

#@schema/desc "bucketrepo for faster download"
bucketrepo:
  enabled: true
  image: jenkinsxio/bucketrepo:0.1.2

#@schema/desc "Enable TAP GUI viewer"
tap_gui_viewer:
  enabled: true
  is_view_cluster: false

#@schema/desc "Place blank pipeline and scan template"
blank_pipeline_and_scan:
  enabled: true
  test_image: alpine
