#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: scdf-install
  namespace: scdf
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting tkcrd"
spec:
  serviceAccountName: kapp-sa
  fetch:
    - imgpkgBundle:
        image: #@ data.values.scdf.package.base_repo + "/scdf-pro-package:" + data.values.scdf.package.version
        secretRef:
          name: scdf-registry
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - config/
        valuesFrom:
          - secretRef:
              name: scdf-values
  deploy:
    - kapp:
        rawOptions:
          - --wait-timeout=10m