#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: scdf-install
  namespace: scdf
spec:
  serviceAccountName: kapp-sa
  fetch:
    - imgpkgBundle:
        image: #@ data.values.scdf.package.base_repo + "/scdf-pro-package:" + data.values.scdf.package.version
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - config/
        valuesFrom:
          - secretRef:
              name: scdf-values
    - kbld:
        paths:
          - '-'
  deploy:
    - kapp:
        rawOptions:
          - --wait-timeout=10m