#@ load("/values-template/aws-services-values.lib.yaml", "aws_services_values")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-services-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(aws_services_values())
