#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

#@ def dex_config():
#@overlay/match missing_ok=True
#@overlay/match-child-defaults missing_ok=True
issuer: #@ "https://dex." + data.values.domain + "/dex"
storage:
  type: kubernetes
  config:
    inCluster: true
enablePasswordDB: true
#@ if data.values.openldap.enabled:
#@ admin_dn = "cn=admin," + data.values.openldap.rootdn
#@ user_dn = "ou=" + data.values.openldap.group + "," + data.values.openldap.rootdn
connectors:
- type: ldap
  id: ldap
  name: LDAP
  config:
    host: openldap:389
    insecureNoSSL: true
    insecureSkipVerify: true
    bindDN: #@ admin_dn
    bindPW: #@ data.values.openldap.adminpassword
    userSearch:
      baseDN: #@ user_dn
      filter: "(objectClass=posixAccount)"
      username: uid
      idAttr: uidNumber
      nameAttr: uid
      emailAttr: mail
      preferredUsernameAttr: uid
    groupSearch:
      baseDN: #@ user_dn
      filter: "(objectClass=groupOfNames)"
      userMatchers:
      - userAttr: DN
        groupAttr: member
      nameAttr: cn
logger:
  level: "debug"
#@ end
staticClients:
- id: dex-authenticator
  name: dex-authenticator
  secret: #@ data.values.static.secret
  redirectURIs: #@ data.values.static.callbacks
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret","metadata": {"name": "dex"}})
---
data:
  #@overlay/replace via=lambda a,b: base64.encode("{}".format(yaml.encode(overlay.apply(dex_config()))))
  config.yaml:

#@overlay/match by=overlay.all, expects="1+"
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind": "ClusterRoleBinding","metadata": {"name": "dex-cluster"}})
---
subjects:
#@overlay/match by="name"
- name: dex
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind": "RoleBinding","metadata": {"name": "dex"}})
---
subjects:
#@overlay/match by="name"
- name: dex
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/append
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace



