apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: k8s-operators.tanzu.japan.com
spec:
  displayName: "Tanzu K8s Operators"
  shortDescription: "Tanzu K8s Operators"
  supportDescription: "https://carvel.dev/"
  providerName: "Broadcom"
  maintainers:
  - name: "Machi Hoshino"
