#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: pvc-owned-for-deletion-strategy-overlay
  namespace: #@ data.values.tp.namespace
stringData:
  #@yaml/text-templated-strings
  pvc-owned-for-deletion-strategy.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind": "PersistentVolumeClaim"}), expects="0+"
    ---
    #@overlay/match missing_ok=True
    metadata:
      #@overlay/match missing_ok=True
      #@overlay/match-child-defaults missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        kapp.k14s.io/owned-for-deletion: ""
  statefulset-owned-for-deletion-strategy.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@ def add_name(left):
      #@ for i in range(len(left)):
      #@overlay/match by=overlay.index(i)
      #@overlay/match-child-defaults missing_ok=True
    - metadata:
        annotations:
          kapp.k14s.io/owned-for-deletion: ""
        #@ if ( "metadata" not in left[i] ) or ("name" not in left[i]["metadata"]):
        name: #@ "data-{}".format(i)
        #@ end
      #@ end
    #@ end

    #@overlay/match by=overlay.subset({"kind": "StatefulSet"}), expects="0+"
    ---
    #@overlay/match missing_ok=True
    spec:
      #@overlay/replace via=lambda left, right: overlay.apply(left, add_name(left))
      volumeClaimTemplates: