#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: fix-prometheus-too-small
  namespace: #@ data.values.tp.namespace
stringData:
  fix-prometheus-too-small.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:base64", "base64")
    #@ load("@ytt:yaml", "yaml")

    #@ def add_pvc_size():
    #@overlay/match missing_ok=True
    server:
      persistence:
        size: 8Gi
    #@ end

    #@overlay/match by=overlay.subset({"kind":"Secret", "metadata": {"name": "prometheus-values"}})
    ---
    data:
      #@overlay/replace via=lambda orig, _: base64.encode(yaml.encode(overlay.apply(yaml.decode(base64.decode(orig)),add_pvc_size())))
      values.yaml: