#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: make-tmc-xsmall
  namespace: #@ data.values.tp.namespace
stringData:
  make-tmc-xsmall.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"kind": "PackageInstall", "metadata": {"name": "tmc"}}), expects="1+"
    ---
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        #@overlay/match missing_ok=True
        ext.packaging.carvel.dev/ytt-paths-from-secret-name.9: make-tmc-xsmall-pkgi