#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: make-tmc-xsmall
  namespace: #@ data.values.tp.namespace
stringData:
  make-tmc-xsmall.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:base64", "base64")
    #@ load("@ytt:yaml", "yaml")
    
    #@ def xsmall():
    #@overlay/match missing_ok=True
    size: xsmall
    #@overlay/match missing_ok=True
    createNamespace: false
    #@ end
    
    #@overlay/match by=overlay.subset({"kind":"Secret", "metadata": {"name": "tmc-values"}})
    ---
    data:
      #@overlay/replace via=lambda orig, _: base64.encode(yaml.encode(overlay.apply(yaml.decode(base64.decode(orig)),xsmall())))
      values.yaml: