#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: make-tmc-xsmall-secret
  namespace: #@ data.values.tp.namespace
stringData:
  #@yaml/text-templated-strings
  make-tmc-xsmall-secret.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@ def single_replica(left):
      #@ if ( "replica" in left ):
    replica: 1
      #@ end
    #@ end
    
    #@overlay/match by=overlay.subset({"kind": "Deployment"}), expects="0+"
    ---
    #@overlay/match missing_ok=True
    #@overlay/replace via=lambda left, right: overlay.apply(left, single_replica(left))
    spec: