#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: make-ensemble-read-single-kafka
  namespace: #@ data.values.tp.namespace
stringData:
  make-ensemble-read-single-kafka: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:base64", "base64")
    #@ load("@ytt:yaml", "yaml")
    
    #@ def reduce_ensemble_kafka():
    #@overlay/match-child-defaults missing_ok=True
    ensemble-app-metadata-ingestion:
      kafka:
        internalEvents:
          partitions: 1
          replicationFactor: 1
    #@ end
    
    #@overlay/match by=overlay.subset({"kind":"Secret", "metadata": {"name": "ensemble-helm-values"}})
    ---
    data:
      #@overlay/replace via=lambda orig, _: base64.encode(yaml.encode(overlay.apply(yaml.decode(base64.decode(orig)),reduce_ensemble_kafka())))
      values.yaml: