#@data/values-schema
---
certmanager:
  enabled: true
  package_repo:
    install: false
    repo: projects.registry.vmware.com/tkg/packages/standard/repo
    version: v2024.8.21
  package:
    install: true

openldap:
  enabled: true
  image: index.docker.io/bitnami/openldap@sha256:d78905f12749014709bf6da54192fe74c72686c0e614bfb6e1fa935e66f91d26
  ssl: false
  rootdn: dc=tanzu,dc=net
  adminpassword: adminpassword
  ldif: |
    dn: dc=tanzu,dc=net
    dc: tanzu
    objectClass: dcObject
    objectClass: organization
    o: Tanzu, Inc
    
    dn: ou=core,dc=tanzu,dc=net
    objectClass: organizationalUnit
    ou: core
    
    dn: cn=tpviewer,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpviewer
    sn: TP Viewer
    uid: tpviewer
    mail: tpviewer@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmin,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    cn: tpadmin
    sn: TP Admin
    uid: tpadmin
    mail: tpadmin@tanzu.net
    userPassword: tpsm1!
    
    dn: cn=tpadmins,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpadmins
    description: Tanzu Platform Admins
    member: cn=tpadmin,ou=core,dc=tanzu,dc=net
    
    dn: cn=tpviewers,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tpviewers
    description: Tanzu Platform Viewer
    member: cn=tpviewer,ou=core,dc=tanzu,dc=net
tp:
  flavor: essentials
  profile: evaluation
  version: '10.1.0-asteroid-rc.89-v59b5eec'
  storage_class: tkg-ds
  hack:
    add_limit_to_clickhouse: false
    change_pvc_orphan_delete_strategy: true
    reduce_kafka_replica: true
    reduce_redis_replica: true
    make_tmc_xsmall: false
    salt_disabled: true
    vcf_disabled: true
    fix_promtheus_too_small: false
  ldap_enabled: true
  rsa_builder:
    openssl_image: index.docker.io/alpine/openssl@sha256:707f1866ecf0f97282d3d6b970e4f464e5df9fb41b38df7865311372411bc2e2
    kubectl_image: index.docker.io/bitnami/kubectl@sha256:ddae2364f2addae0524add6e973faf8890391bb642da5fa7e2f02d072559d3f8
  ingress:
    host: tp.example.com
    self_signed_cert: true
    certificate: ""
    privateKey: ""
  imageRegistry:
    server: harbor.example.com
    username: admin
    password: ""
    repo: tpk8s/10.1.0
  organization:
    name: default
  namespace: tanzusm
  oauthProviders: [{}]
  TanzuIntelligentAssist:
    enable: "False"
