#@data/values-schema
---
namespace: gpss-install

repo:
  url: helm-gpss-operator
  user: ""
  password: ""
repo_password: ""
version: 1.0.0
controller:
  repo:
    url: controller
  version: 1.0.0


