#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"etcd"}}), expects="2+"
---
metadata:
  namespace: gpss-install

#@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata":{"name":"etcd"}}), expects="1+"
---
spec:
  replicas: 1