#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"etcd"}}), expects="2+"
---
metadata:
  namespace: gpss-install

#@overlay/match by=overlay.subset({"kind":"StatefulSet", "metadata":{"name":"etcd"}}), expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      affinity:
        podAntiAffinity:
          #@overlay/remove
          requiredDuringSchedulingIgnoredDuringExecution:
          #@overlay/match missing_ok=True
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: etcd
                topologyKey: kubernetes.io/hostname
              weight: 100