#@ load("values-template/tap-values.lib.yaml", "tap_values")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
stringData:
  values.yaml: #@ yaml.encode(tap_values())
