apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tmc-sm.tanzu.japan.com.1.0.0
spec:
  refName: tmc-sm.tanzu.japan.com
  version: 1.0.0
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tmc-sm.tanzu.japan.com/1.0.0
      template:
      - ytt: {}
      deploy:
      - kapp: {}
