#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.gemfire.package.install:
apiVersion: v1
kind: Namespace
metadata:
  name: gemfire-install
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-registry
  namespace: gemfire-install
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: gemfire-install
secrets:
  - name: tap-registry
imagePullSecrets:
  - name: tap-registry
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gemfire-kapp-role-binding
  namespace: gemfire-install
subjects:
- kind: ServiceAccount
  name: kapp-sa
  namespace: gemfire-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gemfire
  namespace: gemfire-install
spec:
  serviceAccountName: kapp-sa
  fetch:
  - imgpkgBundle:
      image:  #@ data.values.gemfire.package.repo.url + ":" + data.values.gemfire.package.version
      secretRef:
        name: tap-registry
    path: gemfire/
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - gemfire/operator.yaml
      - gemfire/certificates.yaml
      - gemfire/functions.lib.yml
      inline:
        paths:
          values-update.yaml: |
            #@data/values
            ---
            namespace: gemfire-install
            name: gemfire-operator
            certManagerNamespace: ""
            cpu: ""
            memory: ""
            imagePullSecretName: "tap-registry"
            tlsSecretName: ""
            registry:
              server: ""
              username: ""
              password: ""
  deploy:
    - kapp: {}
#@ end
