concourse:
  web:
    externalUrl: https://example.com
    auth:
      mainTeam:
        config: "aaa"
      github:
         enabled: true

secrets:
  githubClientId: dummy
  githubClientSecret: dummy
  localUsers: dummy:dummy
