#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: tmc-values-generated-secrets
  namespace: tmc-local
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: postgres-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: postgres-pass
    - name: minio-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: postgres-pass
    - name: tmc-cert
      ref:
        apiVersion: v1
        kind: Secret
        name: tmc-cert
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        postgres:
          userPassword: #@ base64.decode("$(.postgres-pass.data.pass)")
        minio:
          password: #@ base64.decode("$(.minio-pass.data.pass)")
        trustedCAs:
          local-ca.crt: #@ base64.decode("$(.tmc-cert.data.tls\.crt)")
---
apiVersion: v1
kind: Secret
metadata:
  name: tmc-values-generated-secrets
  namespace: tmc-local
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"