#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ def tmc_values():

clusterIssuer: tmc-local-issuer
createNamespace: false
contourEnvoy:
  serviceType: LoadBalancer

size: #@ data.values.tmc.size
dnsZone: #@ data.values.domain
harborProject: #@ data.values.tmc.imageRegistry.server + "/" + data.values.tmc.imageRegistry.repo
authenticationType: ldap
oidc:
  issuerType: pinniped
  issuerURL: #@ "https://pinniped-supervisor." + data.values.domain + "/provider/pinniped"

ldap:
  type: "ldap"
  host: "openldap.openldap.svc.cluster.local:636"
  username: #@ data.values.openldap.adminUserDN
  domainName: "in-cluster-openldap"
  userBaseDN: #@ data.values.openldap.userBaseDN
  userSearchFilter: #@ data.values.openldap.userSearchFilter
  groupBaseDN: #@ data.values.openldap.groupBaseDN
  groupSearchFilter: #@ data.values.openldap.groupSearchFilter
minio:
  username: admin
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tmc-values
  namespace: tmc-local
stringData:
  #@yaml/text-templated-strings
  data-values.yaml: |
    #@data/values
    ---
    (@= yaml.encode(tmc_values())@)
