#@data/values-schema
---
domain: example.com

certmanager:
  enabled: true
  package_repo:
    install: false
    repo: projects.registry.vmware.com/tkg/packages/standard/repo
    version: v2024.8.21
  package:
    install: true

tmc:
  size: small
  version: 1.4.0
  imageRegistry:
    server: harbor.example.com
    repo: tmc

openldap:
  enabled: true
  image: index.docker.io/bitnami/openldap@sha256:d78905f12749014709bf6da54192fe74c72686c0e614bfb6e1fa935e66f91d26
  ssl: true
  rootdn: "dc=tanzu,dc=net"
  userBaseDN: "ou=core,dc=tanzu,dc=net"
  groupBaseDN: "dc=tanzu,dc=net"
  adminUserDN: "cn=admin,dc=tanzu,dc=net"
  userSearchFilter: "(&(objectClass=inetOrgPerson)(uid={}))"
  groupSearchFilter: "(&(objectClass=groupOfNames)(member={}))"
  ldif: |
    dn: dc=tanzu,dc=net
    dc: tanzu
    objectClass: dcObject
    objectClass: organization
    o: Tanzu, Inc
    
    dn: ou=core,dc=tanzu,dc=net
    objectClass: organizationalUnit
    ou: core
    
    dn: cn=tmcviewer,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: tmcviewer
    sn: TMC Viewer
    uid: tmcviewer
    uidNumber: 1001
    gidNumber: 1001
    mail: tmcviewer@tanzu.net
    userPassword: tmcsm1!
    homeDirectory: /home/tmcviewer
    
    dn: cn=tmcadmin,ou=core,dc=tanzu,dc=net
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: tmcadmin
    sn: TMC Admin
    uid: tmcadmin
    uidNumber: 1000
    gidNumber: 1000
    mail: tmcadmin@tanzu.net
    userPassword: tmcsm1!
    homeDirectory: /home/tmcadmin
    
    dn: cn=tmc:admin,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tmc:admin
    description: Tanzu Admins
    member: cn=tmcadmin,ou=core,dc=tanzu,dc=net
    
    dn: cn=tmc:member,dc=tanzu,dc=net
    objectClass: top
    objectClass: groupOfNames
    cn: tmc:member
    description: Tanzu Viewer
    member: cn=tmcviewer,ou=core,dc=tanzu,dc=net