#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: scdf-install
  namespace: #@ data.values.namespace
spec:
  serviceAccountName: scdf-kapp-sa
  fetch:
    - inline:
        pathsFrom:
          - secretRef:
              name: scdf-values
          - secretRef:
              name: scdf-values-generated-secrets
      path: values/
    - imgpkgBundle:
        image: #@ data.values.repo.url + "/scdf-pro-package:" + data.values.version
        secretRef:
          name: repo-secret
      path: scdf
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - scdf/config/
          - values/data-values.yaml
          - values/secret-values.yaml
  deploy:
    - kapp:
        rawOptions:
          - --wait-timeout=10m