#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: scdf-install
  namespace: #@ data.values.namespace
spec:
  serviceAccountName: scdf-kapp-sa
  fetch:
    - imgpkgBundle:
        image: #@ data.values.repo.url + "/scdf-pro-package:" + data.values.version
        secretRef:
          name: repo-secret
  template:
    - ytt:
        ignoreUnknownComments: true
        inline:
          pathsFrom:
            - secretRef:
                name: scdf-values
            - secretRef:
                name: scdf-values-generated-secrets
        paths:
          - config/
          - data-values.yaml
          - secret-values.yaml
  deploy:
    - kapp:
        rawOptions:
          - --wait-timeout=10m