#@ load("@ytt:data", "data")


---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: postgres-helm
  namespace: #@ data.values.namespace
spec:
  serviceAccountName: kapp-sa
  fetch:
    - image:
        url:  #@ data.values.repo.url + ":" + data.values.version
        secretRef:
          name: repo-secret
      path: postgres/
  template:
    - helmTemplate:
        path: postgres/vmware-sql-postgres-operator/
        valuesFrom:
          - secretRef:
              name: change-default-reg-secret
  deploy:
    - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: change-default-reg-secret
  namespace: #@ data.values.namespace
stringData:
  change-default-reg-secret.yml: | 
    dockerRegistrySecretName: repo-secret



