#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: harbor-core-ver-1
  namespace: tanzu-system-registry
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  toNamespace: #@ data.values.namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: harbor-core-ver-1
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  fromNamespace: openldap
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: harbor-core-ver-1
  namespace: tanzu-system-registry
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  toNamespace: #@ data.values.namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: tbs-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: harbor-core-ver-1
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-core-ver-1
    - name: harbor-tls
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-tls
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        shared:
          image_registry:
            username: admin
            password: #@ base64.decode("$(.harbor-core-ver-1.data['HARBOR_ADMIN_PASSWORD'])")
            ca_cert:　#@ base64.decode("$(.harbor-tls.data.ca\.crt)")
---
apiVersion: v1
kind: Secret
metadata:
  name: tmc-values-generated-secrets
  namespace: tmc-local
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"