#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ count = data.values.rabbitmq.count + 1
#@ for j in range(1,count):
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: #@ "rmq-" + str(j)
spec:
  imagePullSecrets:
    - name: tap-registry
  rabbitmq:
    additionalPlugins:
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_k8s
#@ end
