#@data/values-schema
---
crossplane:
  aws:
   repo: xpkg.upbound.io/upbound/provider-family-aws
   tag: v0.38.0
  ecs:
   repo: xpkg.upbound.io/upbound/provider-aws-ecs
   tag: v0.38.0
  ec2:
   repo: xpkg.upbound.io/upbound/provider-aws-ec2
   tag: v0.38.0
  elbv2:
   repo: xpkg.upbound.io/upbound/provider-aws-elbv2
   tag: v0.38.0

aws:
  accountId: ""
  roleName: "tap-ecs"
  cluster: ""
  region: us-west-2
  vpcId: vpc-xxxxx
  alb:
    enabled: true
    public: true
    subnets:
    - subnet1
  ecs:
    public: false
    subnets:
    - private-subnet1
