#@data/values-schema
---
crossplane:
  aws:
   repo: xpkg.upbound.io/upbound/provider-family-aws
   tag: v0.38.0
  ecs:
   repo: xpkg.upbound.io/upbound/provider-aws-ecs
   tag: v0.38.0

aws:
  accountId: ""
  roleName: "tap-ecs"
  cluster: ""
  region: us-west-2
  subnet:
  - sample-subnet1
