#@data/values-schema
---
crossplane:
  aws:
   repo: crossplane/provider-aws
   tag: v0.42.0
  ecs:
   repo: xpkg.upbound.io/upbound/provider-aws-ecs
   tag: v0.38.0

aws:
  accountId: ""
  roleName: "tap-ecs"
  region: us-west-2
