apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tpk8s-opinionated.tanzu.japan.com.10.0.0
spec:
  refName: tpk8s-opinionated.tanzu.japan.com
  version: 10.0.0
  valuesSchema:
    openAPIv3:
      title: tmc-sm.tanzu-jp values schema
      properties:
        certmanager:
          type: object
          additionalProperties: false
          properties:
            enabled:
              type: boolean
              default: true
            package_repo:
              type: object
              additionalProperties: false
              properties:
                install:
                  type: boolean
                  default: false
                repo:
                  type: string
                  default: projects.registry.vmware.com/tkg/packages/standard/repo
                version:
                  type: string
                  default: 2.2.0
            package:
              type: object
              additionalProperties: false
              properties:
                install:
                  type: boolean
                  default: true
        openldap:
          type: object
          additionalProperties: false
          properties:
            enabled:
              type: boolean
              default: true
            ssl:
              type: boolean
              default: false
            rootdn:
              type: string
              default: dc=tp,dc=dev
            group:
              type: string
              default: usergroups
            adminpassword:
              type: string
              default: adminpassword
            ldif:
              type: string
              default: |
                dn: dc=tp,dc=dev
                objectClass: dcObject
                objectclass: organization
                o: tp
                dc: tp

                dn: ou=usergroups,dc=tp,dc=dev
                objectClass: organizationalUnit
                objectClass: top
                ou: usergroups

                dn: cn=tp01,ou=usergroups,dc=tp,dc=dev
                cn: tp01
                sn: tp01
                objectClass: inetOrgPerson
                objectClass: posixAccount
                objectClass: shadowAccount
                userPassword: VMware1!
                uid: tp01
                mail: tp01@tp.com
                uidNumber: 1000
                gidNumber: 1000
                homeDirectory: /home/tp01

                dn: cn=tp:admin,ou=usergroups,dc=tp,dc=dev
                cn: tp:admin
                objectClass: groupOfNames
                member: cn=tp01,ou=usergroups,dc=tp,dc=dev
        tp:
          type: object
          additionalProperties: false
          properties:
            flavor:
              type: string
              default: full
            profile:
              type: string
              default: evaluation
            version:
              type: string
              default: 10.0.0-oct-2024-rc.533-vc0bb325
            storage_class:
              type: string
              default: tkg-ds
            keep_pvc:
              type: boolean
              default: false
            ingress:
              type: object
              additionalProperties: false
              properties:
                host:
                  type: string
                  default: tp.example.com
                self_signed_cert:
                  type: boolean
                  default: true
                certificate:
                  type: string
                  default: ""
                privateKey:
                  type: string
                  default: ""
            salt_disabled:
              type: boolean
              default: true
            vcf_disabled:
              type: boolean
              default: true
            imageRegistry:
              type: object
              additionalProperties: false
              properties:
                server:
                  type: string
                  default: harbor.example.com
                username:
                  type: string
                  default: admin
                password:
                  type: string
                  default: ""
                repo:
                  type: string
                  default: tpk8s/10.0.0
            organization:
              type: object
              additionalProperties: false
              properties:
                name:
                  type: string
                  default: default
            namespace:
              type: string
              default: tanzusm
            ldap_enabled:
              type: boolean
              default: true
            oauthProviders:
              type: array
              items:
                type: object
                additionalProperties: false
                properties:
                  name:
                    type: string
                    default: ad
                  certificate:
                    type: string
                    default: ""
                  configUrl:
                    type: string
                    default: ""
                  issuerUrl:
                    type: string
                    default: ""
                  scopes:
                    type: array
                    items:
                      type: string
                      default: ""
                    default: []
                  loginPageLinkText:
                    type: string
                    default: Microsoft AD
                  clientId:
                    type: string
                    default: ""
                  secret:
                    type: string
                    default: ""
                  attributeMappings:
                    type: object
                    additionalProperties: false
                    properties:
                      username:
                        type: string
                        default: email
                      groups:
                        type: string
                        default: groups
              default: []
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tpk8s-opinionated.tanzu.japan.com/10.0.0
      template:
      - ytt: {}
      deploy:
      - kapp: {}
