#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: tp-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: redis-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: clickhouse-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: postgres-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-access-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-readonly-access-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-secret-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 40
  digits: 10
  uppercaseLetters: 10
  lowercaseLetters: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: seaweed-readonly-secret-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 40
  digits: 10
  uppercaseLetters: 10
  lowercaseLetters: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
#! https://github.gwd.broadcom.net/TNZ/ensemble-observability-store/blob/master/tss-server/src/main/java/com/vmware/aria/tss/server/validation/UUID.java
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-1
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 8
  symbols: 8
  symbolCharSet: "1234567890abcdef"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-2
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 4
  symbols: 4
  symbolCharSet: "1234567890abcdef"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-3
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 1
  symbols: 1
  symbolCharSet: "12345"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-4
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 3
  symbols: 3
  symbolCharSet: "1234567890abcdef"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-5
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 1
  symbols: 1
  symbolCharSet: "89ab"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-6
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 3
  symbols: 3
  symbolCharSet: "1234567890abcdef"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: organization-id-7
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 12
  symbols: 12
  symbolCharSet: "1234567890abcdef"
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: encryption-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: tp-app-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: ensemble-user-service-pass
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
#! https://github.gwd.broadcom.net/TNZ/ensemble-self-managed/commit/21c9659029dbce9c01c36a3f44947e0ea0a90b44
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: notifications-encryption-key
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)