apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-toolkit-starter.tanzu.japan.com.1.3.2
spec:
  refName: tap-toolkit-starter.tanzu.japan.com
  version: 1.3.2
  valuesSchema:
    openAPIv3:
      title: tap-toolkit-starter.tanzu-jp values schema
      properties:
        domain:
          type: string
          description: domain_name
        sso_redirect_urls:
          type: array
          description: app sso redirect urls
        sso_testuser_enabled:
          type: boolean
          default: false
          description: Enable test users
        sso_providers:
          type: object
          default: []
          description: SSO providers
        storage_class:
          type: string
          description: storage class
        rabbitmq_enabled:
          type: boolean
          description: Enable rabbitmq
          default: false
        postgres_enabled:
          type: boolean
          description: Enable postgres
          default: false
        gemfire_enabled:
          type: boolean
          description: Enable gemfire
          default: false
  template:
    spec:
      fetch:
      - inline:
          paths:
            config/base.yaml: |
              ---
              apiVersion: services.apps.tanzu.vmware.com/v1alpha1
              kind: ClusterInstanceClass
              metadata:
                name: secrets
              spec:
                description:
                  short: It's a set of Secrets!
                pool:
                  kind: Secret
                  labelSelector:
                    matchLabels:
                      claimable: "true"
              ---
              apiVersion: services.apps.tanzu.vmware.com/v1alpha1
              kind: ResourceClaimPolicy
              metadata:
                name: secrets-cross-namespace
                namespace: service-instances
              spec:
                consumingNamespaces:
                - '*'
                subject:
                  kind: Secret
                  group: "" 
              ---
              apiVersion: v1
              kind: Namespace
              metadata:
                name: service-instances
              ---
              apiVersion: v1
              kind: Secret
              metadata:
                name: tap-registry
                namespace: service-instances
                annotations:
                  secretgen.carvel.dev/image-pull-secret: ""
              type: kubernetes.io/dockerconfigjson
              data:
                .dockerconfigjson: e30K
              ---
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: default
                namespace: service-instances
              secrets:
                - name: tap-registry
              imagePullSecrets:
                - name: tap-registry
              ---
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRole
              metadata:
                name: resource-claims-secret
                labels:
                  servicebinding.io/controller: "true"
              rules:
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["get", "list", "watch"]
        path: config/
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config/
          inline:
            paths:
              overlay.yaml: |
                #@ load("@ytt:data", "data")
                #@ load("@ytt:overlay", "overlay")

                #@ if data.values.rabbitmq_enabled:
                ---
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: resource-claims-rmq
                  labels:
                    servicebinding.io/controller: "true"
                rules:
                - apiGroups: ["rabbitmq.com"]
                  resources: ["rabbitmqclusters"]
                  verbs: ["get", "list", "watch"]
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ClusterInstanceClass
                metadata:
                  name: rabbitmq
                spec:
                  description:
                    short: It's a RabbitMQ cluster!
                  pool:
                    group: rabbitmq.com
                    kind: RabbitmqCluster
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ResourceClaimPolicy
                metadata:
                  name: rabbitmqcluster-cross-namespace
                  namespace: service-instances
                spec:
                  consumingNamespaces:
                  - '*'
                  subject:
                    group: rabbitmq.com
                    kind: RabbitmqCluster
                #@ for j in range(1,5):
                ---
                apiVersion: rabbitmq.com/v1beta1
                kind: RabbitmqCluster
                metadata:
                  name: #@ "rmq-" + str(j)
                  namespace: service-instances
                spec:
                  imagePullSecrets: 
                  - name: tap-registry
                  rabbitmq:
                    additionalPlugins:
                      - rabbitmq_shovel
                      - rabbitmq_shovel_management
                      - rabbitmq_management
                      - rabbitmq_prometheus
                      - rabbitmq_peer_discovery_k8s
                #@ end
                #@ end
                
                #@ if data.values.postgres_enabled:
                ---
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: resource-claims-postgres
                  labels:
                    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
                rules:
                - apiGroups: ["sql.tanzu.vmware.com"]
                  resources: ["postgres"]
                  verbs: ["get", "list", "watch", "update"]
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ClusterInstanceClass
                metadata:
                  name: postgres
                spec:
                  description:
                    short: It's a Postgres cluster!
                  pool:
                    group: sql.tanzu.vmware.com
                    kind: Postgres
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ResourceClaimPolicy
                metadata:
                  name: postgrescluster-cross-namespace
                  namespace: service-instances
                spec:
                  consumingNamespaces:
                  - '*'
                  subject:
                    group: sql.tanzu.vmware.com
                    kind: Postgres
                #@ for j in range(1,5):
                ---
                apiVersion: sql.tanzu.vmware.com/v1
                kind: Postgres
                metadata:
                  name: #@ "postgres-1" + str(j)
                  namespace: service-instances
                spec:
                  memory: 400Mi
                  cpu: "0.4"
                  storageSize: 10G
                  storageClassName: #@ data.values.storage_class
                  monitorStorageClassName: #@ data.values.storage_class
                  postgresVersion:
                    name: postgres-14
                  highAvailability:
                    enabled: false
                #@ end
                #@ end

                #@ if data.values.gemfire_enabled:
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ClusterInstanceClass
                metadata:
                  name: gemfire
                spec:
                  description:
                    short: It's a Gemfire cluster !
                  pool:
                    kind: Secret
                    labelSelector:
                      matchLabels:
                        gemfire: "true"
                ---
                apiVersion: v1
                kind: Secret
                metadata:
                  name: image-pull-secret
                  namespace: service-instances
                  annotations:
                    secretgen.carvel.dev/image-pull-secret: ""
                type: kubernetes.io/dockerconfigjson
                data:
                  .dockerconfigjson: e30K
                #@ for j in range(1,5):
                ---
                apiVersion: gemfire.vmware.com/v1
                kind: GemFireCluster
                metadata:
                  name: #@ "gemfire-redis" + str(j)
                  namespace: service-instances
                spec:
                  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.1
                  antiAffinityPolicy: None
                  security:
                    tls: {}
                  metrics:
                    emission: Default
                  locators:
                    replicas: 1
                    resources:
                      requests:
                        memory: 1Gi
                  servers:
                    replicas: 1
                    resources:
                      requests:
                        memory: 1Gi
                    libraries:
                      - name: gemfire-for-redis-apps
                        container:
                          image: registry.tanzu.vmware.com/tanzu-gemfire-for-redis-apps/gemfire-for-redis-apps:1.0.1
                          path: "/gemfire-for-redis-apps/*"
                          imagePullSecretRef:
                            name: image-pull-secret
                    overrides:
                      jvmOptions: ["-Dgemfire-for-redis-enabled=true"]
                ---
                apiVersion: v1
                kind: Secret
                metadata:
                  name: #@ "gemfire-redis" + str(j)
                  namespace: service-instances
                  labels:
                    gemfire: "true"
                type: servicebinding.io/redis
                stringData:
                  type: redis
                  cluster.nodes: #@ "gemfire-redis" + str(j) + "-server-0.gemfire-redis" + str(j) + "-server.service-instances:6379"
                #@ end
                #@ end
                
                ---
                apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
                kind: AuthServer
                metadata:
                  name: basic-authserver
                  namespace: service-instances
                  labels:
                    name: basic-authserver
                  annotations:
                    sso.apps.tanzu.vmware.com/allow-client-namespaces: "service-instances"
                    sso.apps.tanzu.vmware.com/allow-unsafe-issuer-uri: ""
                    sso.apps.tanzu.vmware.com/allow-unsafe-identity-provider: ""
                spec:
                  replicas: 1
                  issuerURI: #@ "https://authserver." + data.values.domain	
                  tokenSignature:
                    signAndVerifyKeyRef:
                      name: "authserver-signing-key"
                  identityProviders:
                    #@ if data.values.sso_testuser_enabled:
                    #@overlay/match by="name", missing_ok=True
                    - name: "internal"
                      internalUnsafe:
                        users:
                          - username: "user"
                            password: "{bcrypt}$2a$10$201z9o/tHlocFsHFTo0plukh03ApBYe4dRiXcqeyRQH6CNNtS8jWK"
                    #@ end
                    #@ for sso_provider in data.values.sso_providers:
                    #@overlay/match by="name", missing_ok=True
                    - #@ sso_provider
                    #@ end
                ---
                apiVersion: secretgen.k14s.io/v1alpha1
                kind: RSAKey
                metadata:
                  name: authserver-signing-key
                  namespace: service-instances
                spec:
                  secretTemplate:
                    type: Opaque
                    stringData:
                      key.pem: $(privateKey)
                      pub.pem: $(publicKey)
                ---
                apiVersion: v1
                kind: Service
                metadata:
                  name: basic-authserver
                  namespace: service-instances 
                  annotations:
                    kapp.k14s.io/disable-default-label-scoping-rules: ""
                spec:
                  selector:
                    app.kubernetes.io/part-of: basic-authserver
                    app.kubernetes.io/component: authorization-server
                  ports:
                    - port: 80
                      targetPort: 8080
                ---
                apiVersion: projectcontour.io/v1
                kind: HTTPProxy
                metadata:
                  name: basic-authserver
                  namespace: service-instances
                spec:
                  virtualhost:
                    fqdn: #@ "authserver." + data.values.domain
                    tls:
                      secretName: tanzu-system-ingress/cnrs-default-tls
                  routes:
                    - conditions:
                        - prefix: /
                      services:
                        - name: basic-authserver
                          port: 80
                ---
                apiVersion: sso.apps.tanzu.vmware.com/v1alpha1
                kind: ClientRegistration
                metadata:
                   name: basic-client-registration
                   namespace: service-instances
                spec:
                   authServerSelector:
                      matchLabels:
                         name: basic-authserver
                   redirectURIs: #@ data.values.sso_redirect_urls
                   requireUserConsent: false
                   clientAuthenticationMethod: basic
                   authorizationGrantTypes:
                      - client_credentials
                      - authorization_code
                   scopes:
                      - name: "openid"
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ClusterInstanceClass
                metadata:
                  name: appsso
                spec:
                  description:
                    short: It's a SSO service!
                  pool:
                    group: sso.apps.tanzu.vmware.com
                    kind: ClientRegistration
                ---
                apiVersion: services.apps.tanzu.vmware.com/v1alpha1
                kind: ResourceClaimPolicy
                metadata:
                  name: appsso-cross-namespace
                  namespace: service-instances
                spec:
                  consumingNamespaces:
                  - '*'
                  subject:
                    group: sso.apps.tanzu.vmware.com
                    kind: ClientRegistration
      deploy:
        - kapp: {}
