#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
data:
  values.yml: #@ base64.encode(yaml.encode(data.values.supplychain.values))
kind: Secret
metadata:
  name: #@ "ootb-supply-chain-" + data.values.ootb_supplychain + "-w-kbld-values"
  namespace: tap-install
type: Opaque
