#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")

#@ def dockerhub_config_fragment(user, password):
username: #@ user
password: #@ password
#@ end

#@ def dockerhub_config(url, user, password):
#@ docker_config = { url.partition("/")[0] : dockerhub_config_fragment(user, password)}
auths: #@ docker_config
#@ end
---
apiVersion: v1
kind: Namespace
metadata:
  name: tdf-install
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-secret
  namespace: tdf-install
type: kubernetes.io/dockerconfigjson
#@ repo = data.values.repo
data:
  #@ url = repo.url
  #@ user = repo.user
  #@ password = repo.password
  .dockerconfigjson: #@ base64.encode(json.encode(dockerhub_config(url, user, password)))
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: repo-secret
  namespace: tdf-install
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: tdf-install
secrets:
  - name: repo-secret
imagePullSecrets:
  - name: repo-secret
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ "{}-kapp-role-binding".format("tdf-install")
  namespace: tdf-install
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: tdf-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin