#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:json", "json")
#@ load("@ytt:base64", "base64")

#@ def dockerhub_config_fragment(user, password):
username: #@ user
password: #@ password
#@ end

#@ def dockerhub_config(url, user, password):
#@ docker_config = { url.partition("/")[0] : dockerhub_config_fragment(user, password)}
auths: #@ docker_config
#@ end
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: tdf-helm
  namespace: tdf-install
spec:
  serviceAccountName: kapp-sa
  fetch:
    - image:
        url:  #@ data.values.repo.url + ":" + data.values.version
        secretRef:
          name: repo-secret
      path: tdf/
    - inline:
        paths:
          kapp-config.yaml: |
            apiVersion: kapp.k14s.io/v1alpha1
            kind: Config
            changeGroupBindings:
              - name: tdf-install
                resourceMatchers:
                  - kindNamespaceNameMatcher: {kind: Deployment, namespace: tdf-install, name: tdf-helm-dataflow-server}
                  - kindNamespaceNameMatcher: {kind: Deployment, namespace: tdf-install, name: tdf-helm-dataflow-server}
            changeRuleBindings:
              - name: smoke-test
                resourceMatchers:
                  - kindNamespaceNameMatcher: {kind: Pod, namespace: tdf-install, name: tdf-helm-dataflow-smoke-test}
                rules:
                  - "upsert after upserting tdf-install"
  template:
    - helmTemplate:
        path: tdf/dataflow/
        valuesFrom:
          - secretRef:
              name: change-default-reg-secret
  deploy:
    - kapp: {}
---
#@ def tdf_values():
deployer:
  imagePullSecrets:
  -  tanzu-dataflow-registry-secret

database:
  mysql:
    enabled: false
  postgresql:
    imagePullSecretName: tanzu-dataflow-registry-secret
    enabled: true

rabbitmq:
  imagePullSecretName: tanzu-dataflow-registry-secret
server:
  configuration:
    containerRegistries:
      ghcr:
        registry-host: ghcr.io
        authorization-type: dockeroauth2
      tanzu-dataflow:
        registry-host: tanzu-dataflow-docker.packages.broadcom.com
        authorization-type: dockeroauth2
        user: #@ data.values.repo.user
        secret: #@ data.values.repo.password

  ingress:
    enabled: #@ data.values.ingress.enabled
    hostname: #@ data.values.ingress.domain
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

skipper:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: change-default-reg-secret
  namespace: tdf-install
stringData:
  #@yaml/text-templated-strings
  change-default-reg-secret.yml: |
     (@= yaml.encode(tdf_values())@)
---
apiVersion: v1
kind: Secret
metadata:
  name: image-repo-secret
  namespace: tdf-install
type: kubernetes.io/dockerconfigjson
#@ repo = data.values.imageRepo
data:
  #@ url = repo.url
  #@ user = repo.user
  #@ password = repo.password
  .dockerconfigjson: #@ base64.encode(json.encode(dockerhub_config(url, user, password)))
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: image-repo-secret
  namespace: tdf-install
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-dataflow-docker-repo-secret
  namespace: tdf-install
type: kubernetes.io/dockerconfigjson
#@ repo = data.values.repo
data:
  #@ url = "tanzu-dataflow-docker.packages.broadcom.com"
  #@ user = repo.user
  #@ password = repo.password
  .dockerconfigjson: #@ base64.encode(json.encode(dockerhub_config(url, user, password)))
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-dataflow-docker-repo-secret
  namespace: tdf-install
spec:
  toNamespaces:
    - "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-dataflow-registry-secret
  namespace: tdf-install
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
    
    
    
    
    