#@data/values-schema
---
#@schema/desc "TLS config"
tls:
  enabled: false
  crt: dummy
  key: dummy

#@schema/desc "Developer namespaces"
#@schema/default ["dev_ns1"]
dev_namespaces: ["dev_ns1"]

#@schema/desc "imageops credentials"
imageops:
  enabled: true
  registry: dummy
  username: dummy
  password: dummy

#@schema/desc "gitops credentials"
gitops:
  enabled: true
  url: dummy
  username: dummy
  password: dummy

#@schema/desc "bucketrepo for faster download"
bucketrepo:
  enabled: true
  image: jenkinsxio/bucketrepo

#@schema/desc "Enable TAP GUI viewer"
tap_gui_viewer:
  enabled: true
  is_view_cluster: false

#@schema/desc "Place blank pipeline and scan template"
blank_pipeline_and_scan:
  enabled: true
  test_image: alpine

