#@ load("@ytt:data", "data")

#@ def imageoverlay():
yaml: |
  #@ load("@ytt:overlay", "overlay")
  
  #! makes an assumption that tap-gui is deployed in the namespace: "tap-gui"
  #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "server", "namespace": "tap-gui"}}), expects="1+"
  ---
  spec:
    template:
      spec:
        containers:
          #@overlay/match by=overlay.subset({"name": "backstage"}),expects="1+"
          #@overlay/match-child-defaults missing_ok=True
          - image: IMAGETOREPLACE
          #@overlay/replace
            args:
            - -c
            - |
              export KUBERNETES_SERVICE_ACCOUNT_TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
              exec /layers/tanzu-buildpacks_node-engine-lite/node/bin/node portal/dist/packages/backend  \
              --config=portal/app-config.yaml \
              --config=portal/runtime-config.yaml \
              --config=/etc/app-config/app-config.yaml
#@ end

#@ final_image = data.values.backstage.publish.repo + '/tdp-configurator-' + data.values.backstage.namespace + ':latest'

#@ if data.values.backstage.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: tdp-app-image-overlay-secret
  namespace: tap-install
stringData:
  tdp-app-image-overlay.yaml: #@ imageoverlay()['yaml'].replace("IMAGETOREPLACE", final_image)
#@ end