#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

#@ def tpb_config():
app:
  plugins:
    - name: #@ data.values.backstage.plugin.name
      version: #@ data.values.backstage.plugin.version
backend:
  plugins: []
#@ end

#@ if data.values.backstage.enabled:
#@   if data.values.backstage.deploy:
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdp-configurator
  namespace: #@ data.values.backstage.workload.namespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdp-configurator
    #@ if data.values.backstage.workload.hastests:
    apps.tanzu.vmware.com/has-tests: "true"
    #@ end
spec:
  build:
    env:
      - name: BP_OCI_REVISION
        value: #@ data.values.backstage.workload.image
      - name: BP_NODE_RUN_SCRIPTS
        value: 'set-tpb-config,portal:pack'
      - name: TPB_CONFIG
        value: /tmp/tpb-config.yaml
      - name: TPB_CONFIG_STRING
        value: #@ base64.encode(yaml.encode(tpb_config()))
  source:
    image: #@ data.values.backstage.workload.image
    subPath: builder
#@   end
#@ end