apiVersion: kapp.k14s.io/v1alpha1
kind: Config

rebaseRules:
- path: [metadata, annotations, crossplane.io/external-create-pending]
  type: copy
  sources: [new, existing]
  resourceMatchers: &ecs
  - apiVersionKindMatcher:
      apiVersion: ecs.aws.crossplane.io/v1alpha1
      kind: TaskDefinition
  - apiVersionKindMatcher:
      apiVersion: ecs.aws.crossplane.io/v1alpha1
      kind: Service

- path: [metadata, annotations, crossplane.io/external-create-succeeded]
  type: copy
  sources: [new, existing]
  resourceMatchers: *ecs

- path: [metadata, annotations, crossplane.io/external-name]
  type: copy
  sources: [new, existing]
  resourceMatchers: *ecs

- path: [metadata, annotations, kbld.k14s.io/images]
  type: copy
  sources: [new, existing]
  resourceMatchers: *ecs

waitRules:
- supportsObservedGeneration: true
  conditionMatchers:
  - type: Ready
    status: "True"
    success: true
  resourceMatchers: *ecs
