apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-swagger2url-supplychain.tanzu.japan.com.1.4.0
spec:
  refName: tap-swagger2url-supplychain.tanzu.japan.com
  version: 1.4.0
  valuesSchema:
    openAPIv3:
      title: tap-swagger2url-supplychain.tanzu-jp values schema
      properties:
        git:
          type: object
          additionalProperties: false
          properties:
            repository:
              type: string
              default: ""
            branch:
              type: string
              default: main
            username:
              type: string
              default: supplychain
            email:
              type: string
              default: supplychain
            commit_message:
              type: string
              default: supplychain@cluster.local
        image:
          type: object
          additionalProperties: false
          properties:
            scripting_base:
              type: string
              default: registry.tanzu.vmware.com/ootb-templates/scripting-base@sha256:72dddaea72f572810d325aa6754da040d5d00e246f11cfdd1a7bcefdca071e43
            openapi_generator:
              type: string
              default: openapitools/openapi-generator-cli
            kpack_kp:
              type: string
              default: kpack/kp
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tap-swagger2url-supplychain.tanzu.japan.com/1.4.0
      template:
      - ytt: {}
      deploy:
      - kapp: {}
