#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-core-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-core-xsrfkey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 32
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-database-password
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-admin-password
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-jobservice-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-registry-secret
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 20
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: harbor-secretkey
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  length: 16
  secretTemplate:
    type: Opaque
    stringData:
      pass: $(value)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: harbor-values-generated-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: harbor-core-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-core-secret
    - name: harbor-core-xsrfkey
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-core-xsrfkey
    - name: harbor-database-password
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-database-password
    - name: harbor-admin-password
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-admin-password
    - name: harbor-jobservice-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-jobservice-secret
    - name: harbor-registry-secret
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-registry-secret
    - name: harbor-secretkey
      ref:
        apiVersion: v1
        kind: Secret
        name: harbor-secretkey
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        core:
          secret: #@ base64.decode("$(.harbor-core-secret.data.pass)")
          xsrfKey: #@ base64.decode("$(.harbor-core-xsrfkey.data.pass)")
        database:
          password: #@ base64.decode("$(.harbor-database-password.data.pass)")
        harbor-admin-password: #@ base64.decode("$(.harbor-admin-password.data.pass)")
        jobservice:
          secret: #@ base64.decode("$(.harbor-jobservice-secret.data.pass)")
        registry:
          secret: #@ base64.decode("$(.harbor-registry-secret.data.pass)")
        secretKey: #@ base64.decode("$(.harbor-secretkey.data.pass)")
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-values-secrets
  namespace: #@ data.values.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"