#@ load("@ytt:data", "data")

#@ if data.values.rabbitmq.enabled:
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq01
  namespace: #@ data.values.namespace
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop: [ "ALL" ]
            initContainers:
              - name: setup-container
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop: [ "ALL" ]
            securityContext:
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
    service:
      spec:
        ports:
          - port: 5552
            targetPort: 5552
            name: stream
  imagePullSecrets:
    - name: regsecret
  tls:
    secretName: rmq01-tls
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_peer_discovery_k8s
      - rabbitmq_shovel
      - rabbitmq_shovel_management
---
#@ if data.values.rabbitmq.contour.enabled:
  #@ for config in [ [ "amqp", "tcp", 5672 ], [ "console", "http", 15672], ["stream", "tcp", 5552] ]:
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: #@ "rmq01-{}".format(config[0])
  namespace: #@ data.values.namespace
spec:
  virtualhost:
    fqdn: #@ "rmq01-{}.{}".format(config[0], data.values.rabbitmq.contour.domain)
    #@ if config[1] == "tcp":
    tls:
      passthrough: true
  tcpproxy:
    services:
      - name: rmq01
        port: #@ config[2]
    #@ else:
  routes:
   - services:
       - name: rmq01
         port: #@ config[2]
    #@ end
  #@ end
#@ end
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: collector
  namespace: #@ data.values.namespace
spec:
  name: collector
  type: fanout
  durable: true
  rabbitmqClusterReference:
    name: rmq01
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: stream1
  namespace: #@ data.values.namespace
spec:
  name: stream1
  type: stream
  arguments:
    x-max-length-bytes: 100000000
  durable: true
  rabbitmqClusterReference:
    name: rmq01
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: stream-binding
  namespace: #@ data.values.namespace
spec:
  source: collector
  destination: stream1
  destinationType: queue
  rabbitmqClusterReference:
    name: rmq01
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: gpss-user-credentials
  namespace: #@ data.values.namespace
spec:
  length: 20
  digits: 5
  uppercaseLetters: 5
  lowercaseLetters: 10
  secretTemplate:
    type: Opaque
    stringData:
      username: gpss-user
      password: $(value)
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: gpss-user
  namespace: #@ data.values.namespace
spec:
  rabbitmqClusterReference:
    name: rmq01
  importCredentialsSecret:
    name: gpss-user-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: gpss-user-permission
  namespace: #@ data.values.namespace
spec:
  vhost: "/"
  user: "gpss-user"
  permissions:
    read: ".*"
  rabbitmqClusterReference:
    name: rmq01
#@ end