#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:yaml", "yaml")

#@ def kbld():
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
  - image: controller:latest
    newImage: #@ data.values.controller.repo.url + ":" + data.values.controller.version
    preresolved: true
#@ end
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: gpss-helm
  namespace: #@ data.values.namespace
spec:
  serviceAccountName: kapp-sa
  fetch:
    - image:
        url:  #@ data.values.repo.url + ":" + data.values.version
        secretRef:
          name: repo-secret
      path: gpss/
    - inline:
        paths:
          kbld.yaml: #@ yaml.encode(kbld())
      path: kbld/
  template:
    - helmTemplate:
        path: gpss/gpss-operator/
        valuesFrom:
          - secretRef:
              name: gpss-helm-values
    - kbld:
        paths:
          - "-"
          - kbld/kbld.yaml
  deploy:
    - kapp: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: gpss-helm-values
  namespace: #@ data.values.namespace
stringData:
  gpss-helm-values.yml: |
    imagePullSecrets:
    - name: "repo-secret"


