apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: rabbitmq.tanzu.japan.com.4.1.0
spec:
  refName: rabbitmq.tanzu.japan.com
  version: 4.1.0
  valuesSchema:
    openAPIv3:
      title: rabbitmq.tanzu-jp values schema
      properties:
        namespace:
          type: string
          default: rabbitmq-install
        repo:
          type: object
          additionalProperties: false
          properties:
            url:
              type: string
              default: rabbitmq-kubernetes.packages.broadcom.com/tanzu-rabbitmq-package-repo
            user:
              type: string
              default: ""
            password:
              type: string
              default: ""
        version:
          type: string
          default: 4.1.0
        operator_version:
          type: string
          default: 4.1.0
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/rabbitmq.tanzu.japan.com/4.1.0
      template:
      - ytt: {}
      deploy:
      - kapp: {}
