apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: rabbitmq.tanzu.japan.com
spec:
  displayName: "Tanzu RabbitMQ"
  shortDescription: "Tanzu RabbitMQ"
  supportDescription: "https://carvel.dev/"
  providerName: "Broadcom"
  maintainers:
  - name: "Machi Hoshino"
