apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-ecs-supplychain.tanzu.japan.com.1.6.1
spec:
  refName: tap-ecs-supplychain.tanzu.japan.com
  version: 1.6.1
  valuesSchema:
    openAPIv3:
      title: tap-ecs.tanzu-jp values schema
      properties:
        crossplane:
          type: object
          additionalProperties: false
          properties:
            aws:
              type: object
              additionalProperties: false
              properties:
                repo:
                  type: string
                  default: xpkg.upbound.io/upbound/provider-family-aws
                tag:
                  type: string
                  default: v0.42.0
            ecs:
              type: object
              additionalProperties: false
              properties:
                repo:
                  type: string
                  default: xpkg.upbound.io/upbound/provider-aws-ecs
                tag:
                  type: string
                  default: v0.42.0
        aws:
          type: object
          additionalProperties: false
          properties:
            accountId:
              type: string
              default: ""
            roleName:
              type: string
              default: tap-ecs
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tap-ecs-supplychain.tanzu.japan.com/1.6.1
      template:
      - ytt: {}
      deploy:
      - kapp: {}
