#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: tp-values-generated-secrets
  namespace: #@ data.values.tp.namespace
spec:
  inputResources:
    - name: tp-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: tp-pass
    - name: redis-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: redis-pass
    - name: clickhouse-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: clickhouse-pass
    - name: postgres-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: postgres-pass
    - name: seaweed-access-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-access-key
    - name: seaweed-readonly-access-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-readonly-access-key
    - name: seaweed-secret-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-secret-key
    - name: seaweed-readonly-secret-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-readonly-secret-key
    - name: organization-id
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id
    - name: encryption-key
      ref:
        apiVersion: v1
        kind: Secret
        name: encryption-key
    - name: inter-ca-cert
      ref:
        apiVersion: v1
        kind: Secret
        name: inter-ca-cert
    - name: rsa-key
      ref:
        apiVersion: v1
        kind: Secret
        name: rsa-key
    - name: jwt-key
      ref:
        apiVersion: v1
        kind: Secret
        name: jwt-key
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        ---
        ingress:
          tls:
            certificate: #@ base64.decode("$(.inter-ca-cert.data.crt\.pem)")
            privateKey: #@ base64.decode("$(.inter-ca-cert.data.key\.pem)")
        postgresql:
          password: #@ base64.decode("$(.postgres-pass.data.pass)")
        clickhouse:
          password: #@ base64.decode("$(.clickhouse-pass.data.pass)")
        redis:
          password: #@ base64.decode("$(.redis-pass.data.pass)")
        seaweedfsS3:
          accessKey: #@ base64.decode("$(.seaweed-access-key.data.pass)")
          secretKey: #@ base64.decode("$(.seaweed-secret-key.data.pass)")
          readOnlyAccessKey: #@ base64.decode("$(.seaweed-readonly-access-key.data.pass)")
          readOnlySecretKey: #@ base64.decode("$(.seaweed-readonly-secret-key.data.pass)")
        login:
          defaultUsers:
            admin:
              password: #@ base64.decode("$(.tp-pass.data.pass)")
        organization:
          id: #@ base64.decode("$(.organization-id.data.pass)")
        cas:
          encryptionKey: #@ base64.decode("$(.encryption-key.data.pass)")
        rsa:
          privateKey: #@ base64.decode("$(.rsa-key.data.key\.pem)")
          publicKey: #@ base64.decode("$(.rsa-key.data.pub\.pem)")
        uaa:
          oauthClients:
            tp_app:
              secret: #@ base64.decode("$(.tp-app-pass.data.pass)")
            tp_cli_app:
              secret: tanzu_intentionally_not_a_secret
            ensemble_user_service:
              secret: tanzu_intentionally_not_a_secret
        tpsmClients:
          tp_app:
            secret: #@ base64.decode("$(.tp-app-pass.data.pass)")
          tp_cli_app:
            secret: tanzu_intentionally_not_a_secret
          ensemble_user_service:
            secret: #@ base64.decode("$(.ensemble-user-service-pass.data.pass)")
        jwt:
          keys:
            tp:
              key: #@ base64.decode("$(.jwt-key.data.key\.pem)")
---
apiVersion: v1
kind: Secret
metadata:
  name: tp-values-generated-secrets
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/exists: ""