#@ load("@ytt:data", "data")
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: tp-values-generated-secrets
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/change-group: "secrettemplate"
spec:
  inputResources:
    - name: tp-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: tp-pass
    - name: redis-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: redis-pass
    - name: clickhouse-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: clickhouse-pass
    - name: postgres-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: postgres-pass
    - name: seaweed-access-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-access-key
    - name: seaweed-readonly-access-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-readonly-access-key
    - name: seaweed-secret-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-secret-key
    - name: seaweed-readonly-secret-key
      ref:
        apiVersion: v1
        kind: Secret
        name: seaweed-readonly-secret-key
    - name: organization-id-1
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id-1
    - name: organization-id-2
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id-2
    - name: organization-id-3
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id-3
    - name: organization-id-4
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id-4
    - name: organization-id-5
      ref:
        apiVersion: v1
        kind: Secret
        name: organization-id-5
    - name: encryption-key
      ref:
        apiVersion: v1
        kind: Secret
        name: encryption-key
    - name: tp-cert
      ref:
        apiVersion: v1
        kind: Secret
        name: tp-cert
    - name: rsa-key
      ref:
        apiVersion: v1
        kind: Secret
        name: rsa-key
    - name: jwt-key
      ref:
        apiVersion: v1
        kind: Secret
        name: jwt-key
    - name: tp-app-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: tp-app-pass
    - name: ensemble-user-service-pass
      ref:
        apiVersion: v1
        kind: Secret
        name: ensemble-user-service-pass
  template:
    stringData:
      secret-values.yaml: |
        #@ load("@ytt:base64", "base64")
        #@data/values
        #@overlay/match-child-defaults missing_ok=True
        ---
        ingress:
          tls:
            certificate: #@ base64.decode("$(.tp-cert.tls\.crt)")
            privateKey: #@ base64.decode("$(.tp-cert.tls\.key)")
        postgresql:
          password: #@ base64.decode("$(.postgres-pass.data.pass)")
        clickhouse:
          password: #@ base64.decode("$(.clickhouse-pass.data.pass)")
        redis:
          password: #@ base64.decode("$(.redis-pass.data.pass)")
        seaweedfsS3:
          accessKey: #@ base64.decode("$(.seaweed-access-key.data.pass)")
          secretKey: #@ base64.decode("$(.seaweed-secret-key.data.pass)")
          readOnlyAccessKey: #@ base64.decode("$(.seaweed-readonly-access-key.data.pass)")
          readOnlySecretKey: #@ base64.decode("$(.seaweed-readonly-secret-key.data.pass)")
        login:
          defaultUsers:
            admin:
              password: #@ base64.decode("$(.tp-pass.data.pass)")
        organization:
          id: #@ base64.decode("$(.organization-id-1.data.pass)") + "-" + base64.decode("$(.organization-id-2.data.pass)") + "-" + base64.decode("$(.organization-id-3.data.pass)") + "-" + base64.decode("$(.organization-id-4.data.pass)") + "-" + base64.decode("$(.organization-id-5.data.pass)")   
        cas:
          encryptionKey: #@ base64.decode("$(.encryption-key.data.pass)")
        rsa:
          privateKey: #@ base64.decode("$(.rsa-key.data.key\.pem)")
          publicKey: #@ base64.decode("$(.rsa-key.data.pub\.pem)")
        uaa:
          oauthClients:
            tp_app:
              secret: #@ base64.decode("$(.tp-app-pass.data.pass)")
            tp_cli_app:
              secret: tanzu_intentionally_not_a_secret
            ensemble_user_service:
              secret: #@ base64.decode("$(.ensemble-user-service-pass.data.pass)")
          tpsmClients:
            tp_app:
              secret: #@ base64.decode("$(.tp-app-pass.data.pass)")
            tp_cli_app:
              secret: tanzu_intentionally_not_a_secret
            ensemble_user_service:
              secret: #@ base64.decode("$(.ensemble-user-service-pass.data.pass)")
          jwt:
            keys:
              tp:
                key: #@ base64.decode("$(.jwt-key.data.key\.pem)")
---
apiVersion: v1
kind: Secret
metadata:
  name: tp-values-generated-secrets
  namespace: #@ data.values.tp.namespace
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "secret"
    kapp.k14s.io/change-rule: "upsert after upserting secrettemplate"