#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")

#@ def dockerhub_config_fragment():
username: #@ data.values.tmc.imageRegistry.username
password: #@ data.values.tmc.imageRegistry.password
#@ end

#@ docker_config = { data.values.tmc.imageRegistry.server : dockerhub_config_fragment()}

#@ def dockerhub_config():
auths: #@ docker_config
#@ end
---
apiVersion: v1
kind: Namespace
metadata:
  name: tmc-local
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Secret
metadata:
  name: registrysecret
  namespace: tmc-local
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ base64.encode("{}".format(yaml.decode(yaml.encode(dockerhub_config()))))
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registrysecret
  namespace: tmc-local
spec:
  toNamespaces:
    - "tmc-local"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: tmc-local
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tmc-kapp-role-binding
  namespace: tmc-local
subjects:
- kind: ServiceAccount
  name: kapp-sa
  namespace: tmc-local
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-mission-control-packages
  namespace: tmc-local
  annotations:
    kapp.k14s.io/change-group: "tmcpkgr"
spec:
  fetch:
    imgpkgBundle:
      image: #@  data.values.tmc.imageRegistry.server + "/" + data.values.tmc.imageRegistry.repo + "/package-repository:" + data.values.tmc.version
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tmc
  namespace: tmc-local
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: tmc-values
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.1: tmc-values-generated-secrets
    kapp.k14s.io/change-rule: "upsert after upserting tmcpkgr"
spec:
  serviceAccountName: kapp-sa
  packageRef:
    refName: tmc.tanzu.vmware.com
    versionSelection:
      constraints: ">0.0.0"
