#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapp-sa
  namespace: #@ data.values.namespace
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: #@ "{}-kapp-role-binding".format(data.values.namespace)
  namespace: #@ data.values.namespace
subjects:
  - kind: ServiceAccount
    name: kapp-sa
    namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
#@ for pkg in ["cert-manager", "contour", "harbor", "gemfire", "gpss", "postgres", "rabbitmq"]:
  #@ if data.values[pkg].install:
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: #@ "{}-pkg".format(pkg)
  namespace: #@ data.values.namespace
  annotations:
    #@ change_group=""
    #@ change_rule=""
    #@ if pkg == "cert-manager":
    #@  change_group="cert-manager"
    #@ elif pkg == "contour":
    #@  change_group="contour"
    #@  change_rule="upsert after upserting cert-manager"
    #@ else:
    #@  change_rule="upsert after upserting contour"
    #@ end
    #@ if/end change_group != "":
    kapp.k14s.io/change-group: #@ change_group
    #@ if/end change_rule != "":
    kapp.k14s.io/change-rule: #@ change_rule
spec:
  serviceAccountName: kapp-sa
  packageRef:
    refName: #@ "{}.{}".format(pkg, data.values[pkg].ref_suffix)
    versionSelection:
      constraints: ">0.0.0"
  values:
    - secretRef:
        name: #@ "{}-values".format(pkg)
        key: values.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: #@ "{}-values".format(pkg)
  namespace: #@ data.values.namespace
stringData:
  values.yml: #@ yaml.encode(data.values[pkg].package)
  #@ end
#@ end
