apiVersion: v1
kind: Secret
metadata:
  name: add-w-kbld-supplychain # secret name referred in annotation
  namespace: tap-install
stringData:
  add-w-kbld-supplychain.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"kind": "ClusterSupplyChain"})
    ---
    metadata:
      #@overlay/replace via=lambda a,_: a+"-w-kbld"
      name:
    spec:
      selectorMatchExpressions:
      #@overlay/append
      - key: withKbld
        operator: Exists
      resources:
      #@overlay/match by=overlay.subset({"name": "config-writer"})
      - templateRef:
          name: config-writer-w-kbld
