apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-yaml2source-supplychain.tanzu.japan.com.1.3.4
spec:
  refName: tap-yaml2source-supplychain.tanzu.japan.com
  version: 1.3.4
  valuesSchema:
    openAPIv3:
      title: tap-yaml2source-supplychain.tanzu-jp values schema
      properties:
        jenkins:
          type: object
          description: jenkins object
          properties:
            url:
              type: string
              description: jenkins url
            username:
              type: string
              description: jenkins username
            password:
              type: string
              description: jenkins password
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/mhoshi-vm/tap-carvel
          ref: origin/pkgr
          subPath: manifests/tap-yaml2source-supplychain.tanzu.japan.com/1.3.4
      template:
      - ytt: {}
      deploy:
      - kapp: {}
