#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if data.values.gitops.enabled:
#@ namespaces = data.values.dev_namespaces
#@ for namespace in namespaces:
#@overlay/append
---
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh
  namespace: #@ namespace
  annotations:
    tekton.dev/git-0: #@ data.values.gitops.url
type: kubernetes.io/basic-auth 
stringData:
  username: #@ data.values.gitops.username
  password: #@ data.values.gitops.password
#@ end
#@ end
