#@data/values-schema
---
namespace: default

k8soperator:
  package:
    cert-manager:
      install: true
    contour:
      install: false
    gemfire:
      install: false
    gpss:
      install: false
    postgres:
      install: true
      package:
        repo:
          user: ""
          password: ""
    rabbitmq:
      install: true
      package:
        repo:
          user: ""
          password: ""

postgres:
  count: 1
  storage_class: default
  instance_version: "postgres-17"

rabbitmq:
  count: 1

repo:
  url: registry.packages.broadcom.com
  user: ""
  password: ""
version: 1.6.6
task_runner_version: 2.11.8