apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tkgs.tanzu.japan.com.0.0.1
spec:
  refName: tkgs.tanzu.japan.com
  version: 0.0.1
  valuesSchema:
    openAPIv3:
      title: tkgs.tanzu-jp values schema
  template:
    spec:
      fetch:
      - inline:
          paths:
            config/base.yaml: |
              apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                creationTimestamp: null
                name: privileged-cluster-role-binding
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: psp:vmware-system-privileged
              subjects:
              - apiGroup: rbac.authorization.k8s.io
                kind: Group
                name: system:authenticated
        path: config/
      template:
      - ytt:
          ignoreUnknownComments: true
          paths:
          - config/
      deploy:
        - kapp: {}
