apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: tkgs.tanzu.japan.com
spec:
  displayName: "TKGs setup"
  shortDescription: "Setup initial TKGs"
  supportDescription: "https://carvel.dev/"
  providerName: "VMware"
  maintainers:
  - name: "Machi Hoshino"
