#@data/values-schema
---
namespace: harbor-install

domain: example.com

standard:
  package_repo:
    install: false
    repo: projects.packages.broadcom.com/tkg/packages/standard/repo
    version: v2025.6.18

storageClass: default

version: v2.13.1_vmware.1-tkg.1

tlsCertificate: {}