#@ load("@ytt:data", "data")

#@ if data.values.delivery.overlay:
#@ if/end "app-deploy" not in data.values.excluded_templates:
---
apiVersion: carto.run/v1alpha1
kind: ClusterDeploymentTemplate
metadata:
  name: app-deploy-w-kbld
spec:
  params:
    - name: serviceAccount
      default: default

  healthRule:
    multiMatch:
      healthy:
        matchConditions:
          - type: ReconcileSucceeded
            status: 'True'
      unhealthy:
        matchFields:
          - key: 'status.conditions[?(@.type=="ReconcileFailed")].status'
            operator: 'In'
            values: ['True']
            messagePath: '.status.usefulErrorMessage'

  observedCompletion:
    succeeded:
      key: '.status.conditions[?(@.type=="ReconcileSucceeded")].status'
      value: 'True'
    failed:
      key: '.status.conditions[?(@.type=="ReconcileSucceeded")].status'
      value: 'False'

  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:assert", "assert")

    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.deliverable.metadata, "labels"):
    #@     labels.update(data.values.deliverable.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end

    ---
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: #@ data.values.deliverable.metadata.name
      labels: #@ merge_labels({ "app.kubernetes.io/component": "deploy" })
    spec:
      syncPeriod: 10m0s
      serviceAccountName: #@ data.values.params.serviceAccount
      fetch:
        - http:
            url: #@ data.values.deployment.url or assert.fail("missing required deployment config url")
            #@ if hasattr(data.values.deliverable.spec.source, "subPath"):
            subPath: #@ data.values.deliverable.spec.source.subPath
            #@ elif hasattr(data.values.params, "gitops_sub_path"):
            subPath: #@ data.values.params.gitops_sub_path
            #@ end
          path: config/
      template:
      - ytt:
          paths:
            - config/
      - kbld:
          paths:
            - "-"
            - config/.imgpkg/images.yml
      deploy:
        - kapp: {}
#@ end
