#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providerconfigs.aws.upbound.io
  annotations:
    kapp.k14s.io/exists: ""
    kapp.k14s.io/change-group: "crd"
spec:
  group: aws.upbound.io
  versions:
    - name: v1beta1
  names:
    kind: ProviderConfig
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-provider
  annotations:
    kapp.k14s.io/change-rule: "upsert after upserting crd"
spec:
  credentials:
    source: IRSA
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: upbound-provider-aws
  annotations:
    eks.amazonaws.com/role-arn: #@ 'arn:aws:iam::' + data.values.aws.accountId + ':role/' + data.values.aws.roleName
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - '--debug'
    - '--poll=2m'
    - '--max-reconcile-rate=10'
